### ISSUE TITLE
Bug Load fixtures data

### ISSUE THREAD

**Issue by habibun** [sonata-project/sandbox#1083]
i am using ubuntu php 7.4 and master branch

Load fixtures data
after run this command `vendor/bin/phing`

i am getting this error: Property App\Entity\Comment\Comment::$category does not exist

**Comment by g-ra** [comment]
any news ? 
Is it really solved by manually adding category (with getters, setters)?

**Comment by habibun** [comment]
yes, it is. thanks @g-ra

**Comment by g-ra** [comment]
@habibun please reopen issue i will fixe it in pull request
