### ISSUE TITLE
Just trying to install 

### ISSUE THREAD

**Issue by Ziiweb** [sonata-project/sandbox#298]
hi,

running this php composer.phar create-project sonata-project/sandbox:dev-2.3
I get this:

[InvalidArgumentException]  
  Could not find package sonata-project/sandbox with version dev-2.3.

**Comment by codiiv** [comment]
It's been only 2 years and it's still not working!

**Comment by greg0ire** [comment]
There's a fix-installation branch I think.

**Comment by greg0ire** [comment]
> It's been only 2 years and it's still not working!

Also, why don't **you** fix it?

**Comment by codiiv** [comment]
@greg0ire I wasn't aware of the project (sonata) let alone the fix. I am here only because I am trying to finish a project that uses Sonata. Maybe when I find a fix, you can count on me to share with everyone. 

thanks
