### ISSUE TITLE
Symlink MopaBootstrapBundle

### ISSUE THREAD

**Issue by ghost** [sonata-project/sandbox#344]
Hello, 
I'm trying to install Sonata Sandbox, and everytime I try to install, I keep having this error : 

An error occurred while creating symlink C:/wamp/www/sanbox/vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/Public/Bootstrap 

Can you please help ? It's been the 10th time I'm trying to install this !

**Comment by xeux** [comment]
Did not work as administrator (win8), return Permission denied in same MopaBundle.

This is actually old.. what is the workaround? use unix?

**Comment by adrian410** [comment]
Did you find a solution guys ? I keep getting this error "BootstrapBundle\Resources\public\bootstrap)
  : Permission denied"

**Comment by vladkras** [comment]
me too (windows 8.1 + docker)
