### ISSUE TITLE
2.3-dev - Loading of fixtures require big amount of memory

### ISSUE THREAD

**Issue by gam6itko** [sonata-project/sandbox#410]
I have execute this command
```
php app/console doctrine:fixtures:load
```
I have got this error

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 2802 bytes) in D:\02_Development\_git-hub\sonata-admin-sandbox\vendor\doctrine\dbal\lib\Doctrine\DBAL\Statement.php on line 165

**Comment by rande** [comment]
This has been fixed
