### ISSUE TITLE
An error occurs when running a command!

### ISSUE THREAD

**Issue by rexchou** [sonata-project/sandbox#415]
[RuntimeException]
  There is no main category related to context: default

Exception trace:
 () at /mnt/esong/www/sandbox/vendor/sonata-project/media-bundle/Listener/ORM/MediaEventSubscriber.php:82
 Sonata\MediaBundle\Listener\ORM\MediaEventSubscriber->getRootCategory() at /mnt/esong/www/sandbox/vendor/sonata-project/media-bundle/Listener/ORM/MediaEventSubscriber.php:64
 Sonata\MediaBundle\Listener\ORM\MediaEventSubscriber->getMedia() at /mnt/esong/www/sandbox/vendor/sonata-project/media-bundle/Listener/BaseMediaEventSubscriber.php:66
 Sonata\MediaBundle\Listener\BaseMediaEventSubscriber->getProvider() at /mnt/esong/www/sandbox/vendor/sonata-project/media-bundle/Listener/BaseMediaEventSubscriber.php:155
 Sonata\MediaBundle\Listener\BaseMediaEventSubscriber->prePersist() at /mnt/esong/www/sandbox/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php:61
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /mnt/esong/www/sandbox/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php:117
 Doctrine\ORM\Event\ListenersInvoker->invoke() at /mnt/esong/www/sandbox/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:845
 Doctrine\ORM\UnitOfWork->persistNew() at /mnt/esong/www/sandbox/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1627
 Doctrine\ORM\UnitOfWork->doPersist() at /mnt/esong/www/sandbox/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1583
 Doctrine\ORM\UnitOfWork->persist() at /mnt/esong/www/sandbox/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:624
 Doctrine\ORM\EntityManager->persist() at /mnt/esong/www/sandbox/vendor/sonata-project/core-bundle/Model/BaseManager.php:118
 Sonata\CoreBundle\Model\BaseManager->save() at /mnt/esong/www/sandbox/vendor/sonata-project/media-bundle/Entity/MediaManager.php:41
 Sonata\MediaBundle\Entity\MediaManager->save() at /mnt/esong/www/sandbox/src/Sonata/Bundle/DemoBundle/DataFixtures/ORM/LoadMediaData.php:64
 Sonata\Bundle\DemoBundle\DataFixtures\ORM\LoadMediaData->load() at /mnt/esong/www/sandbox/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:121
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load() at /mnt/esong/www/sandbox/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:83
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() at n/a:n/a
 call_user_func() at /mnt/esong/www/sandbox/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:243
 Doctrine\ORM\EntityManager->transactional() at /mnt/esong/www/sandbox/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:85
 Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at /mnt/esong/www/sandbox/vendor/doctrine/doctrine-fixtures-bundle/Doctrine/Bundle/FixturesBundle/Command/LoadDataFixturesDoctrineCommand.php:106
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at /mnt/esong/www/sandbox/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /mnt/esong/www/sandbox/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:896
 Symfony\Component\Console\Application->doRunCommand() at /mnt/esong/www/sandbox/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /mnt/esong/www/sandbox/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /mnt/esong/www/sandbox/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /mnt/esong/www/sandbox/app/console:34

**Comment by rande** [comment]
Cannot reproduce.
