### ISSUE TITLE
The image format "sonata_product_small" is not defined

### ISSUE THREAD

**Issue by igormukhingmailcom** [sonata-project/sandbox#418]
Hi.
Installing 2.4-develop showing next error in browser:

An exception has been thrown during the rendering of a template ("The image format "sonata_product_small" is not defined.
Is the format registered in your `sonata_media` configuration?") in SonataProductBundle:Product:view_thumbnail.html.twig at line 22.

**Comment by jordisala1991** [comment]
Old issue, feel free to reopen if this is still happening on master branch
