### ISSUE TITLE
error installation on windows

### ISSUE THREAD

**Issue by felek000** [sonata-project/sandbox#420]
Hello, i want to install sonata on windows 8 xampp.
I use comand php composer.phar create-project sonata-project/sandbox:2.3.x-dev and after download I get error. I found that error is for me 2 lines:
in bin\load.data.php
1) 'rm -rf ./app/cache/*', i can coment that
2) -d memory_limit=1024M -d max_execution_time=600 ./app/console doctrine:fixtures:load --verbose --env=dev --no-debug i increase memory limit 1024m and time too 600 in php.ini and remove that part still i get error:
I try remove and install database again no result what can i do to solve ?

Executing :  C:\Users\Felek\Desktop\xampp\php\php.exe ./app/console doctrine:fix
tures:load --verbose --env=dev --no-debug
Careful, database will be purged. Do you want to continue Y/N ?

  [RuntimeException]
  Aborted

Exception trace:
 () at C:\Users\Felek\Desktop\xampp\htdocs\sonata\sandbox\vendor\symfony\symfony
\src\Symfony\Component\Console\Helper\DialogHelper.php:115
 Symfony\Component\Console\Helper\DialogHelper->ask() at C:\Users\Felek\Desktop\
xampp\htdocs\sonata\sandbox\vendor\symfony\symfony\src\Symfony\Component\Console
\Helper\DialogHelper.php:242
 Symfony\Component\Console\Helper\DialogHelper->askConfirmation() at C:\Users\Fe
lek\Desktop\xampp\htdocs\sonata\sandbox\vendor\doctrine\doctrine-fixtures-bundle
\Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand.php:73
 Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute
() at C:\Users\Felek\Desktop\xampp\htdocs\sonata\sandbox\vendor\symfony\symfony\
src\Symfony\Component\Console\Command\Command.php:252
 Symfony\Component\Console\Command\Command->run() at C:\Users\Felek\Desktop\xamp
p\htdocs\sonata\sandbox\vendor\symfony\symfony\src\Symfony\Component\Console\App
lication.php:896
 Symfony\Component\Console\Application->doRunCommand() at C:\Users\Felek\Desktop
\xampp\htdocs\sonata\sandbox\vendor\symfony\symfony\src\Symfony\Component\Consol
e\Application.php:193
 Symfony\Component\Console\Application->doRun() at C:\Users\Felek\Desktop\xampp\
htdocs\sonata\sandbox\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\
Console\Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\Users\Felek\D
esktop\xampp\htdocs\sonata\sandbox\vendor\symfony\symfony\src\Symfony\Component\
Console\Application.php:124
 Symfony\Component\Console\Application->run() at C:\Users\Felek\Desktop\xampp\ht
docs\sonata\sandbox\app\console:34

doctrine:fixtures:load [--fixtures[="..."]] [--append] [--em="..."] [--purge-wit
h-truncate]

An error occurs when running a command!

**Comment by rande** [comment]
Cannot reproduce
