### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by craigwillis85** [sonata-project/sandbox#426]
Hi

I have just installed 2.3-dev via composer and get the following:

`An exception has been thrown during the rendering of a template ("Unrecognized field: parent") in SonataBlockBundle:Block:block_core_menu.html.twig at line 15.`

I'm running PHP5.5.15

**Comment by OskarStark** [comment]
use app_dev.php/admin instead of app_dev.php

Oskar

**Comment by jordisala1991** [comment]
Not to much info to fix this
