### ISSUE TITLE
Error in Admin when viewing Categories

### ISSUE THREAD

**Issue by craigwillis85** [sonata-project/sandbox#427]
Hi

Upon recently installing, when I click on `Classification -> Categories` I get the following error:

`[Semantical Error] line 0, col 80 near 'parent IS NU': Error: Class Application\Sonata\ClassificationBundle\Entity\Category has no field or association named parent`

**Comment by hitchen123** [comment]
Yeah I have exactly the same problem

**Comment by jordisala1991** [comment]
Related to ClassificationBundle, probably fixed using 3.0

Closing for now, if this is still relevant, please reopen this issue on the correct bundle.
