### ISSUE TITLE
erro when create Category, cause the field enabled is null default

### ISSUE THREAD

**Issue by cncowboy** [sonata-project/sandbox#429]
INSERT INTO classification__category (name, enabled, slug, description, position, created_at, updated_at, parent_id, media_id) VALUES  
('test',null,'test','test',0,'2014-11-23','2014-11-23',null,null)
the sentence above will fail cause enabled =null
solution:
to set enabled=true in Model category construct function:
    public function __construct()
    {
        $this->enabled = true;
    }

**Comment by rande** [comment]
fixed
