### ISSUE TITLE
Error while loading fixtures

### ISSUE THREAD

**Issue by Rems69** [sonata-project/sandbox#430]
Hi, I'm trying to install Sonata Sandbox on my Mac with PHP5.5 with the following command line : 

> COMPOSER_PROCESS_TIMEOUT=600 php composer.phar create-project sonata-project/sandbox:dev-2.3-develop

All works great until I load fixtures, I get the following error with LoadProductData :

>  loading [12] Sonata\Bundle\DemoBundle\DataFixtures\ORM\LoadProductData
>                                                      
>   [Imagine\Exception\InvalidArgumentException]   An image could not be created from the given input

**Comment by eliysha** [comment]
Hi,

I have the same problem, 

is it solved ?

Thanks

**Comment by Rems69** [comment]
No, it's still unsolved :/

**Comment by grosenbaum** [comment]
@eliysha Do you test the Sonata Sandbox on your Mac too ?
@Rems69 I'm not sure but it doesn't seem to be related to Sonata Sandbox, more probably to some graphical libraries like GD or ImageMagick.

**Comment by eliysha** [comment]
Problem solved for me.

png support wasnt enabled on my GD configuration.
