### ISSUE TITLE
Error in Admin when viewing Categories list in Classification

### ISSUE THREAD

**Issue by zayen** [sonata-project/sandbox#431]
Hi

Upon recently installing, when I click on Classification -> Categories I get the following error:

Impossible to access an attribute ("context") on a NULL variable ("") in SonataClassificationBundle:CategoryAdmin:list_tab_menu.html.twig at line 4

**Comment by pirasterize** [comment]
I've the same issue since longer... even after >> composer update
always there

Even after the command :
app/console  sonata:classification:fix-context
the current_category doesn't have his default context 

Should we miss something in config.yml ?

Thanks from any help

**Comment by rande** [comment]
Cannot reproduce the issue.
