### ISSUE TITLE
installing warning

### ISSUE THREAD

**Issue by cjuhong** [sonata-project/sandbox#433]
Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.
Package stephpy/TimelineBundle is abandoned, you should avoid using it. Use https://packagist.org/packages/stephpy/timeline-bundle instead.

**Comment by grosenbaum** [comment]
These messages are just warnings.
Maybe you could propose a PR to fix these warnings.
Thx

**Comment by rande** [comment]
The  2.3 release will use the deprecated bundle. The upcoming 2.4 release will use the new bundles.
