### ISSUE TITLE
Composer.json missing required BCMath Ext.

### ISSUE THREAD

**Issue by dankempster** [sonata-project/sandbox#435]
Received the following error when installing on a minimalist VM.

    PHP Fatal error:  Call to undefined function bcscale() in /var/www/html/sonatasandbox/app/AppKernel.php on line 14
    PHP Stack trace:
    PHP   1. {main}() /var/www/html/sonatasandbox/app/console:0
    PHP   2. Symfony\Component\HttpKernel\Kernel->__construct() /var/www/html/sonatasandbox/app/console:29
    PHP   3. AppKernel->init() /var/www/html/sonatasandbox/app/bootstrap.php.cache:2309
    Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

The sandbox needs the bcmath extension, but it's not mentioned in the composer.json file.

    "require": {
        "php": ">=5.3.3",
        "ext-bcmath" : "*",
        ...
    }

Full output of command

    [vagrant@dan sonatasandbox (2.3)]$ php -d zend.gc_enabled=0 $(which composer) install --no-dev
    Loading composer repositories with package information
    Installing dependencies from lock file
    Nothing to install or update
    Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.
    Package stephpy/TimelineBundle is abandoned, you should avoid using it. Use https://packagist.org/packages/stephpy/timeline-bundle instead.
    Generating autoload files
    Updating the "app/config/parameters.yml" file
    PHP Fatal error:  Call to undefined function bcscale() in /var/www/html/sonatasandbox/app/AppKernel.php on line 14
    PHP Stack trace:
    PHP   1. {main}() /var/www/html/sonatasandbox/app/console:0
    PHP   2. Symfony\Component\HttpKernel\Kernel->__construct() /var/www/html/sonatasandbox/app/console:29
    PHP   3. AppKernel->init() /var/www/html/sonatasandbox/app/bootstrap.php.cache:2309
    Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

      [RuntimeException]
      An error occurred when executing the "'cache:clear --no-warmup'" command.

**Comment by rande** [comment]
The check has been added to the load_data.php script.
