### ISSUE TITLE
Wrong form.

### ISSUE THREAD

**Issue by Vermond125** [sonata-project/sandbox#438]
Hi! I found one bad thing... 
We cannot create Category because of "Enabled" parameter.
So, there are no form element in "classification-bundle/Admin/CategoryAdmin.php" file.
Solution: add this line to $formMapper:  "->add('enabled', null, array('required' => false))"

**Comment by jordisala1991** [comment]
Not enough info to fix anything, probably related to Classification bundle.

Closing for now, if this is still relevant, please ping me to reopen.
