### ISSUE TITLE
Invalid type for path "sonata_news.comment.notification.emails"

### ISSUE THREAD

**Issue by cyberz** [sonata-project/sandbox#447]
After successful install I got this error:
Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidTypeException' with message 'Invalid type for path "sonata_news.comment.notification.emails". Expected array, but got string' in /var/www/symfony2/sonata/sandbox/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 267

**Comment by Brewal** [comment]
It can be easily fixed by change the `app/config/parameter.yml` file. Replace : 

    sonata_news.comment.emails: my@email.tld

to : 

    sonata_news.comment.emails: 
        - my@email.tld

**Comment by volodymyr-nakvasiuk** [comment]
Thanks

**Comment by Flushdrew** [comment]
Hi , i've got  the same error , ant try to write this : 
# comment options
    comment:
        notification:
            emails:
                - myaccount@gmail.com
            from:     no-reply@opticathome.fr
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

and i try too this: 
# comment options
    comment:
        notification:
            emails:   guiardjulien@gmail.com
            from:     no-reply@opticathome.fr
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

but i still have the same error . Can you help me please?

**Comment by Brewal** [comment]
Your first configuration should work. Otherwise, try to rerun the install and don't miss the `[]`

**Comment by volodymyr-nakvasiuk** [comment]
First config will work but You need to remove `notification`:

comment:
    emails:
        - myaccount@gmail.com
    from:     no-reply@opticathome.fr
    template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

**Comment by Flushdrew** [comment]
still the same error :-(

my sonanta_news.yml is : 

sonata_news:
    title:        Optic At Home - Actualités
    link:         www.opticathome.fr/news
    description:  Votre opticien à domicile
    salt:         %sonata_news.salt%

    # permalink_generator: sonata.news.permalink.category # /party/new-year
    permalink_generator: sonata.news.permalink.date # /2011/12/31/new-year

    # comment options
    comment:
            emails:
                - myaccount@gmail.com
            from:
                - no_reply@opticathome.fr
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~ 

my parameter.yml : 

parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: ThisTokenIsNotSoSecretChangeIt

    # Sonata Admin Options
    sonata_admin.title:             Sonata Project
    sonata_admin.logo_title:        /bundles/sonataadmin/logo_title.png

    # Sonata News Options
    sonata_news.blog_title:         Optic At Home - Actualités
    sonata_news.blog_link:          www.opticathome.fr/news
    sonata_news.blog_description:   Votre opticien à domicile
    sonata_news.salt:               ThisTokenIsNotSoSecretChangeIt
    sonata_news.comment.emails:
        - myaccount@gmail.com
    sonata_news.comment.email_from: 
        - no-reply@opticathome.fr

    # Sonata Media options
    sonata_media.cdn.host:          /uploads/media

    # Sonata User Options
    sonata_user.google_authenticator.server:  demo.sonata-project.org

    # Sonata Page Options
    sonata_page.varnish.command: if [ ! -r "/etc/varnish/secret" ]; then echo "VALID ERROR :/"; else varnishadm -S /etc/varnish/secret -T 127.0.0.1:6082 {{ COMMAND }} "{{ EXPRESSION }}"; fi; # you need to adapt this line to work with your configuration


What's wrong with this?

**Comment by volodymyr-nakvasiuk** [comment]
"sonata_news.comment.email_from" Should be string.

'''
sonata_news.comment.email_from: no-reply@opticathome.fr
'''

If not working try also:

'''
    sonata_news.comment.emails:     [myaccount@gmail.com]
    sonata_news.comment.email_from: no-reply@opticathome.fr
'''

**Comment by Flushdrew** [comment]
i tried both and nothing works.
I'll try to reinstall the sandbox...
thank you

**Comment by Flushdrew** [comment]
ok , so i reinstalled the complete sonata sandbox.First time it was with the quick install.
Everthing is working.
Thank you for your help

**Comment by jordisala1991** [comment]
This is already fixed on 3.0: https://github.com/sonata-project/sandbox/blob/3.0/app/config/parameters.yml.dist#L26

Closing, if you still having this issue, please ping me to reopen
