### ISSUE TITLE
An exception has been thrown during the rendering of a template + postgresql

### ISSUE THREAD

**Issue by mgomez-dgt** [sonata-project/sandbox#450]
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT count(DISTINCT n0_.id) AS sclr0 FROM news__post n0_ LEFT JOIN news__post_tag n2_ ON n0_.id = n2_.post_id LEFT JOIN classification__tag c1_ ON c1_.id = n2_.tag_id LEFT JOIN fos_user_user f3_ ON n0_.author_id = f3_.id ORDER BY n0_.publication_date_start DESC':

SQLSTATE[42803]: Grouping error: 7 ERROR: column "n0_.publication_date_start" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ..._user_user f3_ ON n0_.author_id = f3_.id ORDER BY n0_.public...
^") in SonataAdminBundle:Core:dashboard.html.twig at line 35.

**Comment by jordisala1991** [comment]
This is related to AdminBundle or the OrmAdminBundle, I think it is also probably solved by now, but I cant find the PR.

If you still having this issue, please ping me to reopen
