### ISSUE TITLE
Maximum function nesting level of '100' reached

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/sandbox#457]
I just cloned the 2.4 dev branch, ran composer update and then php bin/load_data.php
Didn't get any errors but when I load the site I get this in the frontpage

 Fatal error: Maximum function nesting level of '100' reached, aborting! in /user/sonata_sandbox/vendor/composer/ClassLoader.php on line 321

or 

Fatal error: Maximum function nesting level of '100' reached, aborting! in /squawka/sonata_sandbox/vendor/twig/twig/lib/Twig/Token.php on line 77

When I go to the admin page I sign in using admin/admin and then I am redirected to the front page (where I see the error again).

Am I doing anything wrong here? I need this working to see if I can understand better how certain things are done in sonata, since the documentation is either missing, does not explain well or the stuff I find is just outdated.

Thanks

**Comment by nlzet** [comment]
Seems to be a default xdebug setting which isn't high enough to run sonata (or some bundles in it).

Just change your php.ini to set: 
<code>xdebug.max_nesting_level = 200</code>

**Comment by AntonioCS** [comment]
Isn't this only for when you do a var_dump of things?

**Comment by nlzet** [comment]
Not only that no, it will do more. From the documentation;

_Xdebug's basic functions include the display of stack traces on error conditions, maximum nesting level protection and time tracking._

**Comment by AntonioCS** [comment]
Ok. Thank I will try doing that.
