### ISSUE TITLE
php app/console fos:user:create

### ISSUE THREAD

**Issue by mgomez-dgt** [sonata-project/sandbox#458]
after filled parameters

Please choose a username:demouser  
Please choose an email:****_@gmail.com  
Please choose a password:**_******

  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: array_search() expects parameter 2 to be array, null given             

fos:user:create [--super-admin] [--inactive] username email password

**Comment by muspelheim** [comment]
@mgomez-dgt Hi, you try create user on project from box or you have custom entity/etc?

**Comment by Zuhayer** [comment]
I had the same issue. I had forgot to call parent::__construct(); in the custom User Entity.

**Comment by jordisala1991** [comment]
doesnt seem to be related to sonata
