### ISSUE TITLE
Abandoned Package Warnings during installation with composer

### ISSUE THREAD

**Issue by zuernBernhard** [sonata-project/sandbox#459]
Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.
Package stephpy/TimelineBundle is abandoned, you should avoid using it. Use https://packagist.org/packages/stephpy/timeline-bundle instead.

**Comment by zuernBernhard** [comment]
Seen in the current "stable" Version

**Comment by zuernBernhard** [comment]
Also seen in dev:

 Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.
Package stephpy/TimelineBundle is abandoned, you should avoid using it. Use https://packagist.org/packages/stephpy/timeline-bundle instead.

**Comment by grosenbaum** [comment]
Duplicate issue. Closed in favour of #433.
