### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by pnegry** [sonata-project/sandbox#477]
Following the instructions in the readme i get this error

> Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - Installation request for sonata-project/ecommerce dev-develop -> satisfiable by sonata-project/ecommerce[dev-develop].
>    - sonata-project/ecommerce dev-develop requires sonata-project/seo-bundle ~2.0@dev -> no matching package found.

>Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

You should probably also make the initial curl to the installer use an https link but whatever, i dont care.

**Comment by rande** [comment]
this has been fixed.
