### ISSUE TITLE
Error on install (03/17/2015)

### ISSUE THREAD

**Issue by lordpato** [sonata-project/sandbox#479]
composer.phar create-project sonata-project/sandbox:2.3.x-dev
Installing sonata-project/sandbox (2.3.x-dev 2bf8c8ce1bc5e838c10b7ab84c90fb08f2ef8560)
  - Installing sonata-project/sandbox (2.3.x-dev 2bf8c8c)
    Cloning 2bf8c8ce1bc5e838c10b7ab84c90fb08f2ef8560

Created project in /tmp/sandbox
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/ecommerce dev-develop -> satisfiable by sonata-project/ecommerce[dev-develop].
    - sonata-project/ecommerce dev-develop requires sonata-project/seo-bundle 2.0.*@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by KailZhang** [comment]
got same problem

**Comment by rande** [comment]
This should be fixed. We also add a new way to quickly install the sandbox: https://github.com/sonata-project/sandbox#quick-installation
