### ISSUE TITLE
Error finishing composer update, sonata sandbox 2.3 (Comoser already updated)

### ISSUE THREAD

**Issue by ej-kun** [sonata-project/sandbox#480]
I'm gettins this error installing sonata sandbox 2.3

PHP Fatal error:  Declaration of Sonata\MediaBundle\Block\GalleryBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /home/everton/Área de Trabalho/Projetos/sandbox/vendor/sonata-project/media-bundle/Block/GalleryBlockService.php on line 0
PHP Stack trace:
PHP   1. {main}() /home/everton/Área de Trabalho/Projetos/sandbox/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/everton/Área de Trabalho/Projetos/sandbox/app/console:34
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/everton/Área de Trabalho/Projetos/sandbox/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /home/everton/Área de Trabalho/Projetos/sandbox/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/everton/Área de Trabalho/Projetos/sandbox/app/bootstrap.php.cache:2344
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /home/everton/Área de Trabalho/Projetos/sandbox/app/bootstrap.php.cache:2565
PHP   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /home/everton/Área de Trabalho/Projetos/sandbox/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:614
PHP   8. JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->process() /home/everton/Área de Trabalho/Projetos/sandbox/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:117
PHP   9. JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->processDefinition() /home/everton/Área de Trabalho/Projetos/sandbox/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:64
PHP  10. class_exists() /home/everton/Área de Trabalho/Projetos/sandbox/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:110
PHP  11. spl_autoload_call() /home/everton/Área de Trabalho/Projetos/sandbox/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:110
PHP  12. Symfony\Component\Debug\DebugClassLoader->loadClass() /home/everton/Área de Trabalho/Projetos/sandbox/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:0

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                             
  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command.

**Comment by rande** [comment]
If you want to try this new process to install the sandbox: https://github.com/sonata-project/sandbox#quick-installation
