### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by fmronan** [sonata-project/sandbox#481]
I 'have many error since yesternay with your new install
first with rm -rf first line in load_dataL.php

Resetting demo, this can take a few minutes
 - Checking Sonata Project's requirements................................OK
 - Cleaning the cache....................................................KO
Fail to run: rm -rf ./app/cache/*
'rm' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
You the error is coming from the sandbox,
please report the issue to https://github.com/sonata-project/sandbox/issues
An error occurs when running a command!
  
and after that I remove this line and delete the cache manualy and I have more error

Resetting demo, this can take a few minutes
 - Checking Sonata Project's requirements................................OK
 - Cleaning the cache....................................................KO
Fail to run: rm -rf ./app/cache/*
'rm' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
You the error is coming from the sandbox,
please report the issue to https://github.com/sonata-project/sandbox/issues
An error occurs when running a command!

**Comment by fmronan** [comment]
last error is 
Resetting demo, this can take a few minutes
 - Checking Sonata Project's requirements................................OK
 - Warming up the production cache.......................................KO
Fail to run: C:\wamp\bin\php\php5.4.12\php.exe ./app/console cache:warmup --env=
prod --no-debug

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate
 64 bytes) in C:\wamp\www\sandbox\app\bootstrap.php.cache on line 2675

Call Stack:
    0.0009     237000   1. {main}() C:\wamp\www\sandbox\app\console:0
    0.4394    3628736   2. Symfony\Component\Console\Application->run() C:\wamp\
www\sandbox\app\console:34
    0.5413    3859296   3. Symfony\Bundle\FrameworkBundle\Console\Application->d
oRun() C:\wamp\www\sandbox\vendor\symfony\symfony\src\Symfony\Component\Console\
Application.php:126
    0.5414    3859600   4. Symfony\Component\HttpKernel\Kernel->boot() C:\wamp\w
ww\sandbox\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\App
lication.php:70
    1.0939    4488336   5. Symfony\Component\HttpKernel\Kernel->initializeContai
ner() C:\wamp\www\sandbox\app\bootstrap.php.cache:2344
  188.3433   87189144   6. Symfony\Component\HttpKernel\Kernel->dumpContainer()
C:\wamp\www\sandbox\app\bootstrap.php.cache:2566
  196.9927   89237448   7. Symfony\Component\HttpKernel\Kernel::stripComments()
C:\wamp\www\sandbox\app\bootstrap.php.cache:2652
  196.9928   89237832   8. token_get_all() C:\wamp\www\sandbox\app\bootstrap.php
.cache:2675

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to all
ocate 64 bytes) in C:\wamp\www\sandbox\app\bootstrap.php.cache on line 2675
PHP Stack trace:
PHP   1. {main}() C:\wamp\www\sandbox\app\console:0
PHP   2. Symfony\Component\Console\Application->run() C:\wamp\www\sandbox\app\co
nsole:34
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() C:\wamp\www
\sandbox\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:12
6
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() C:\wamp\www\sandbox\vendor\
symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() C:\wamp\www\
sandbox\app\bootstrap.php.cache:2344
PHP   6. Symfony\Component\HttpKernel\Kernel->dumpContainer() C:\wamp\www\sandbo
x\app\bootstrap.php.cache:2566
PHP   7. Symfony\Component\HttpKernel\Kernel::stripComments() C:\wamp\www\sandbo
x\app\bootstrap.php.cache:2652
PHP   8. token_get_all() C:\wamp\www\sandbox\app\bootstrap.php.cache:2675
You the error is coming from the sandbox,
please report the issue to https://github.com/sonata-project/sandbox/issues
An error occurs when running a command!

**Comment by MGaetan89** [comment]
I'm also having the memory issue.

**Comment by fourpixels** [comment]
+1

**Comment by rande** [comment]
I removed the linux command and raise memory limit https://github.com/sonata-project/sandbox/commit/6d56c507c00deb400e09301cc2d9ab329247cf7c
