### ISSUE TITLE
login in problem

### ISSUE THREAD

**Issue by niepi** [sonata-project/sandbox#482]
- after install I'm not able to login to the site. 
- the log file shows that the user ist authenticated successfully
- but then I have no logged in user in my session 
- I'm also not able to register a new user, because I always get a "The CSRF token is invalid" error

Any hints what the problem could be?

**Comment by rande** [comment]
Are you using vagrant ? if so, php failed to load/save session from a nfs share.

**Comment by niepi** [comment]
Is there a way how I can fix this?

**Comment by rande** [comment]
change the default path location for session in the config.yml
