### ISSUE TITLE
Call to undefined method Knp\Menu\MenuItem::setCurrentUri()

### ISSUE THREAD

**Issue by gabrielalmeida** [sonata-project/sandbox#484]
Fresh install. Route `/profile` throws an HTTP 500. It logs:

```
FatalErrorException: Error: Call to undefined method Knp\Menu\MenuItem::setCurrentUri() in /Users/me/Sites/mysite/vendor/sonata-project/user-bundle/Block/ProfileMenuBlockService.php line 91
```

Also reported on sonata-project/SonataUserBundle#483, this was fixed by sonata-project/SonataUserBundle@503c244 on August 2014 but never got released.

[KnpMenu](https://github.com/KnpLabs/KnpMenu) has deprecated `setCurrentUri` at `2.0 alpha`([Changelog](https://github.com/KnpLabs/KnpMenu/blob/master/CHANGELOG.md)) and non-deprecated versions are incompatible with other sandbox's dependencies.

The unique way to get this working would be requiring `2.3.*@dev` version of `SonataUserBundle` but it'll throw other errors:

```
Updating dependencies (including require-dev)
  - Removing sonata-project/user-bundle (2.2.4)
  - Installing sonata-project/user-bundle (dev-master 5530bfa)
    Cloning 5530bfad63eedd93a0226fe4132a5445fb161603
.
.
.

PHP Fatal error:  Declaration of Sonata\UserBundle\Block\AccountBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockServiceInterface::validateBlock(Sonata\AdminBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /var/www/sandbox/vendor/sonata-project/user-bundle/Block/AccountBlockService.php on line 110
```

Requiring that specific August commit gets the job done for now..
(`"sonata-project/user-bundle": "dev-master#503c2442b8dee337396407a9374b5732ef6d423c"`) :beers:

**Comment by alsii** [comment]
I have the same problem.

**Comment by Cbruyere** [comment]
I've got the same problem too, anything to do ?

**Comment by wbloszyk** [comment]
Hi, 
It is KnpMenuBundle API problem, change it to 1.* or comment setCurrentUri call method.

**Comment by Cbruyere** [comment]
Well, why not but it's not a good solution I feel. As KnpMenuBundle is used by Sonana/UserBundle, it would be better to have this issue solved ?

**Comment by Soullivaneuh** [comment]
@gabrielalmeida @Cbruyere which fresh install did you use? `2.3`, `2.3-dev` or `2.4-dev`?

**Comment by Cbruyere** [comment]
2.3

**Comment by gabrielalmeida** [comment]
I posted it quite a long ago, can't reproduce/help anymore, sorry. If it helps, I guess it was ```2.3-dev``` as this is the version ```sandbox``` instructs to use at ```README.md```:

```
php composer.phar create-project sonata-project/sandbox:2.3.x-dev
```

**Comment by Soullivaneuh** [comment]
ping @rande 

`2.3` and `2.3-develop` has diverged. Could we merge it?

**Comment by eskimos78** [comment]
I have the same problem in a fresh installation of https://github.com/sonata-project/sandbox-build/archive/master.tar.gz , probably @wbloszyk is a good solution but "composer update" fail for that https://github.com/composer/composer/issues/1898

Can you please help me ?

**Comment by jordisala1991** [comment]
Probably duplicated of: https://github.com/sonata-project/SonataUserBundle/issues/456

Closing for now, if you think this is a different issue, please ping me to reopen.
