### ISSUE TITLE
Sonata\PageBundle\Model\SiteInterface, null given

### ISSUE THREAD

**Issue by wanaoishi** [sonata-project/sandbox#485]
I have just installed the sandbox, and change the site for my own. 
And what ever page I go, I have this exception.

An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Sonata\PageBundle\CmsManager\CmsPageManager::getInternalRoute() must implement interface Sonata\PageBundle\Model\SiteInterface, null given, called in /var/www/vendor/sonata-project/page-bundle/Twig/Extension/PageExtension.php on line 217 and defined") in SonataPageBundle::layout.html.twig at line 17.

the ligne 17 is  : 
                {{ sonata_page_render_container('header', 'global') }}

So I have tried to had or empty the header and nothing.
Any idea?

**Comment by RomainTweaks** [comment]
Have you execut the command line :  php app/console sonata:page:create-site (to create your site for sonata sandbox) ?

And the commande line to generate the pages core route and pages snapshots?

**Comment by ronanguilloux** [comment]
+1 for @RomainTweaks solution, issue may be closed IMHO
