### ISSUE TITLE
error installation on windows (copy of #420)

### ISSUE THREAD

**Issue by UnderDogg** [sonata-project/sandbox#487]
Hi,
MySQL 5.5
I tried to install Sonata Sandbox on my Windows 7, used the following steps:
1. Retrieve the code: ``curl -L github https://github.com/sonata-project/sandbox-build/archive/master.tar.gz | tar xzv``
2. Configure default the ``parameters.yml`` file: ``cp app/config/parameters.yml.dist app/config/parameters.yml``
3. load the data: ``php bin/load_data.php``

At step 3 it goes horribly wrong. Also see issue #420 which was closed, because someone could not reproduce it.

I can reproduce it and can give you a screenshot if you need it.
Problem is, that it only shows : Program Aborted, no details.

<pre>Executing :  C:\xampp\php\php.exe  -d memory_limit=1024M -d max_execution_time=600 ./app/console doctrine:fixtures:load --verbose --env=dev --no-debug
Careful, database will be purged. Do you want to continue Y/N ?

  [RuntimeException]
  Aborted</pre>

<pre>Exception trace:

() at J:\VirtualHosts\Symphony\sandbox-build-master\vendor\symfony\symfony\src\Symfony\Component\Console\Helper\DialogHelper.php:115

Symfony\Component\Console\Helper\DialogHelper->ask() at J:\VirtualHosts\Symphony\sandbox-build-master\vendor\symfony\symfony\src\Symfony\Component\Console\Helper\DialogHelper.php:242

Symfony\Component\Console\Helper\DialogHelper->askConfirmation() at J:\VirtualHosts\Symphony\sandbox-build-master\vendor\doctrine\doctrine-fixtures-bundle\Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand.php:73

Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at J:\VirtualHosts\Symphony\sandbox-build-master\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:257

Symfony\Component\Console\Command\Command->run() at J:\VirtualHosts\Symphony\sandbox-build-master\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:882

Symfony\Component\Console\Application->doRunCommand() at J:\VirtualHosts\Symphony\sandbox-build-master\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:195

Symfony\Component\Console\Application->doRun() at J:\VirtualHosts\Symphony\sandbox-build-master\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:96

Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at J:\VirtualHosts\Symphony\sandbox-build-master\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:126

Symfony\Component\Console\Application->run() at J:\VirtualHosts\Symphony\sandbox-build-master\app\console:34</pre>

It might have something to do with this blog post:
https://coderwall.com/p/staybw/workaround-for-1701-cannot-truncate-a-table-referenced-in-a-foreign-key-constraint-using-doctrine-fixtures-load-purge-with-truncate

And he shows a solution. In the meantime, could you guys re-check this issue. It's reproducible

**Comment by rande** [comment]
The windows support has been improved.
