### ISSUE TITLE
An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by putualgoritma** [sonata-project/sandbox#492]
"An exception has been thrown during the rendering of a template ("Warning: array_key_exists(): The first argument should be either a string or an integer") in SonataProductBundle:Product:view_thumbnail.html.twig at line 33"

**Comment by rande** [comment]
not enough information to reproduce the error

**Comment by darkbluesun** [comment]
I also received this error relating to the filter |number_format_currency(currency). Removing the filter eliminated the error. My currency is set properly in config.yml: (I have tried EUR also)

    sonata_price:
        currency: AUD


    doctrine:
        dbal:
            types:
                json: Sonata\Doctrine\Types\JsonType
                currency: Sonata\Component\Currency\CurrencyDoctrineType

**Comment by darkbluesun** [comment]
I needed to add this (rather dodgy) line to RecursiveArrayAccess.php because a currency object was being passed to this function, rather than just the label.

            if (is_array($array)) {
                // add this line
                if (is_object($index)) $index = $index->getLabel();
                if (array_key_exists($index, $array)) {
                    $array = $array[$index];
                    continue;
                }
            } elseif ($array instanceof \ArrayAccess) {
                if (isset($array[$index])) {
                    $array = $array[$index];
                    continue;
                }
            }

**Comment by DancZer** [comment]
I get this error when php intl extenstion was disabled.
