### ISSUE TITLE
assetic:dump fails on assetic/sonata_admin_css.css

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/sandbox#497]
[Assetic\Exception\FilterException]                                                                                                                          
  An error occurred while running: '/usr/bin/java' '-jar' '.../app/../bin/yuicompressor.jar' '--charset' 'UTF-8' '-o' '/private/var/folders/sr/bx6nhm191q7_fyjs159n75q00000gn/T/YUI-OUT-1tyX5H' '--type' 'css' '/private/var/folders/sr/bx6nhm191q7_fyjs159n75q00000gn/T/YUI-IN-qLnOwl'                                        
  Error Output: Exception in thread "main" java.lang.reflect.InvocationTargetException

**Comment by AlexL5** [comment]
Are you sure yuicompressor.jar is in you /bin folder???  If yes, try
another version of yuicompressor (I know that one version doesn't work
correctly on windows)

**Comment by stphnpt** [comment]
Yes, yuicompressor (v2.4.8) is in my /bin folder and only sonata_admin_css.css cannot be compressed ... (?) Got the same issue with a former version of yuicompressor of october 2014 ...

**Comment by nlzet** [comment]
I experienced a problem with yuicompressor 2.4.8 as well, try changing a failed asset with a minified version of the asset or the other way around.

If you have the same problem as me, try changing (in app/config/assetic.yml):
`                - %kernel.root_dir%/../web/bundles/sonatapage/sonata-page.back.min.css`
to:
`                - %kernel.root_dir%/../web/bundles/sonatapage/sonata-page.back.css`

**Comment by stphnpt** [comment]
thanks nizet for this hint : I changed all the ".min.css" to ".css" in the sonata_admin_css.css file but still get the same exact error message from the java script ...

**Comment by nlzet** [comment]
Hmm not sure it is the same situation then. I debugged it by manually commenting groups of assets to find out on which one it failed.

**Comment by rande** [comment]
The issue is coming from https://github.com/sonata-project/SonataPageBundle/blob/master/Resources/public/sonata-page.back.css#L520-L528

**Comment by rande** [comment]
fixing the code in the PageBundle

**Comment by rande** [comment]
Reference: https://github.com/sonata-project/SonataPageBundle/commit/7b6e60ff03299635d2b4fa91542a8337f462f936
