### ISSUE TITLE
Impossible to access an attribute ("options") on a boolean variable ("")

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/sandbox#499]
Error happens when trying to edit some blocks in the backend:

request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Impossible to access an attribute ("options") on a boolean variable ("") in "SonataAdminBundle:Form:form_admin_fields.html.twig" at line 238" at .../vendor/twig/twig/lib/Twig/Template.php line 403 {"exception":"[object] (Twig_Error_Runtime(code: 0): Impossible to access an attribute (\"options\") on a boolean variable (\"\") in \"SonataAdminBundle:Form:form_admin_fields.html.twig\" at line 238 at .../vendor/twig/twig/lib/Twig/Template.php:403)"} []

**Comment by rande** [comment]
@stphnpt Can you provide information about how to reproduce the issue ?

**Comment by stphnpt** [comment]
@rande I updated my composer.json and cannot reproduce it as of today (that may also have been linked to the fact that I had a block container as a parent of another block container (!?)) ... You may also check if the fieldDescrition options are correctly flown down to the twig templates : for example, something like:
$listMapper->add('history', 'html', array(), array('truncate' => true)) does not lead to the application of the truncate filter even if it is present in the list_html.html.twig view ?

**Comment by stphnpt** [comment]
I still get the same error, but it only happens in the dev environment ...

**Comment by rande** [comment]
duplicate https://github.com/sonata-project/sandbox/issues/488
