### ISSUE TITLE
Problem Installation

### ISSUE THREAD

**Issue by vints24** [sonata-project/sandbox#502]
Hi,
I follow the different steps and i am stopped by this error : 
 - Checking Sonata Project's requirements................................KO
Fail to run: /usr/bin/php -d memory_limit=-1 ./bin/sonata-check.php

I tried to modify the memory_limit in my php.ini but nothing change.

Has someone else experienced this same issue, and/or knows how to fix this?

Thank you for your help.

**Comment by rande** [comment]
You need to run the command `` /usr/bin/php -d memory_limit=-1 ./bin/sonata-check.php`` and check the output.

**Comment by vints24** [comment]
The output : 
OK	gd is installed
OK	gd with jpg support is installed
KO	missing png with jpg support
KO	Missing php-intl extension
OK	Successfully valid Symfony2's requirements
OK	mb_strlen() is available
OK	PDO is available
OK	PDO mysql is available
OK	bcmath extension is available
OK	curl extension is available
OK	xdebug is not available

I don't find something about, may be you have an idea. Thank you.
