### ISSUE TITLE
Creating the class cache KO in load_data.php with pdo_pgsql

### ISSUE THREAD

**Issue by DancZer** [sonata-project/sandbox#505]
parameters:
    database_driver:   pdo_pgsql
    database_host:     127.0.0.1
    database_name:     sonata_sandbox
    database_user:     postgres
    database_password: null
- Creating the class cache..............................................KO
  Fail to run: c:\wamp\bin\php\php5.5.12\php.exe -d memory_limit=-1 ./app/console
  cache:create-cache-class --env=prod --no-debug
  
  [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[08006] [7] FATAL:  database "sonat
  a_sandbox" does not exist
  
  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[08006] [7] FATAL:  database "sonata_sandbox" does not exist
  
  [PDOException]
  SQLSTATE[08006] [7] FATAL:  database "sonata_sandbox" does not exist

**I fixed this with changing the execute commands order. I moved the drop and create database before the create-cache-class.**

**Comment by jordisala1991** [comment]
The new build system should fix this issue on 3.0: https://github.com/sonata-project/sandbox/blob/3.0/build.xml

But it is not documented, thats why I created this: #609 

Closing
