### ISSUE TITLE
Warning message on local windows server Warning: array_key_exists():

### ISSUE THREAD

**Issue by silver619** [sonata-project/sandbox#510]
I am getting this warning in many spots on the demo site:

Warning: array_key_exists(): The first argument should be either a string or an integer in D:\EasyPHP\data\localweb\projects\sonata\vendor\symfony\symfony\src\Symfony\Component\Intl\Data\Util\RecursiveArrayAccess.php on line 28

It occurs wherever there are prices and other spots on the site and i cannot figure out why its happening.

**Comment by Emirii** [comment]
Do you have the Intl extension installed for php?

**Comment by silver619** [comment]
Ok that extension wasn't enabled, that sorted that, is there a list of php requirements for sonata, cause i didn't get any warning about it. Also one other thing. The twitter widget isn't coming up only the link is there a particular extension i need for that as well? Thank you.

**Comment by Soullivaneuh** [comment]
> Also one other thing. The twitter widget i...

@silver619 Please open another ticket for this request.

Closing this one as resolved.
