### ISSUE TITLE
Colored blocks

### ISSUE THREAD

**Issue by Plimsky** [sonata-project/sandbox#512]
Hello all !
It's been a while that I'm trying to figure out how I can configure those colored blocks. But I don't find where.
I need some help, please.

Thanks ! :)

![capture_d ecran_052815_022815_pm](https://cloud.githubusercontent.com/assets/1219936/7860027/df034a56-0545-11e5-8a37-2b58e1ade3ea.jpg)

**Comment by rande** [comment]
https://github.com/sonata-project/sandbox/blob/2.4-develop/app/config/sonata/sonata_admin.yml#L61
