### ISSUE TITLE
Functionnal tests and Travis

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/sandbox#518]
Could be interessting to add functionnal tests with Behat on this sandbox.

We could handle error that cannot be found by bundles' unit tests.

cc @rande

**Comment by rande** [comment]
https://github.com/sonata-project/sandbox/tree/2.3/features ;)

**Comment by Soullivaneuh** [comment]
Well, I need new eyes. :-)

But what about Travis integration?

**Comment by Soullivaneuh** [comment]
Saw the `.travis.yml` but this seems to not be integrated on the repository.

**Comment by rande** [comment]
It is in the 2.4-develop branch. However, there is one test failing on the ecommerce code:  https://github.com/sonata-project/sandbox/tree/2.4-develop

**Comment by rande** [comment]
However, I think I will drop travis support for the sandbox, and use codeship as the solution is very flexible to analyse build error. Also this will allow to push the code to the build branch.

Here the travis build: https://travis-ci.org/sonata-project/sandbox

**Comment by Soullivaneuh** [comment]
Thanks. I know for `2.4-develop` bugs. I'm actually working on it.
