### ISSUE TITLE
Hangs 'loading fixtures'

### ISSUE THREAD

**Issue by redactuk** [sonata-project/sandbox#525]
Second attempt today installing 2.4 development version on local Windows Wamp setup. Installation has far less issues than few days ago since symfony 2.7.1 update plus other stuff, however:

1. Install with composer does not install any data. Is that supposed to be the case? It goes though prompts for database details but nothing installed, so attempted to load manually:

2. Loading data manually with \bin\load_data.php gets to Loading Fixtures step then stops. Left it for well over 20 minutes and still nothing. Any idea how to diagnose why?

I've checked database and all tables seem to have been created ok but no data. I'm guessing this is what the Load Fixtures step is supposed to do.

Thanks

**Comment by rande** [comment]
@redactuk hello, the time might be different depends on the plateforme, you my local machine it tooks less than a minute (VM on OSX), on codeship the process to load composer and the fixtures is about 4min.

If you have a windows you need to check that there is no anti virus scanning the php code, also if you have a slow HD this might not help.

**Comment by redactuk** [comment]
Not sure if this is relevant to point 1, but there was one error on install:

An error occurred while creating symlinkC:\wamp\sandbox\vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle\Resources\public\boostrap

Regarding load data, I'll try again with AV switched off etc...

**Comment by rande** [comment]
@redactuk you need to report the symlink issue to MopaBootstrapBundle

**Comment by DancZer** [comment]
Check this out:
https://github.com/sonata-project/sandbox/pull/506

**Comment by rande** [comment]
@DancZer is `` --no-interaction`` option important ? we don't need it on linux or osx

**Comment by redactuk** [comment]
Yes that works! adding --no-interaction option resolved the issue. Many thanks.

**Comment by rande** [comment]
@redactuk can you print the output of the load fixtures without the --no-interaction option ? seems to be related to windows only

**Comment by redactuk** [comment]
Not sure what you mean? Without that option I don't get past Loading fixtures. With that option it proceeds with remaining steps e.g. Sonata - News: updating comment count etc...

**Comment by rande** [comment]
What prompt do you get when you start: ``-d max_execution_time=600 ./app/console doctrine:fixtures:load --verbose --env=dev --no-debug`` on windows. As --no-interaction option solves your problem, I guess doctrine is waiting something.

**Comment by redactuk** [comment]
I don't get any prompt. It just sits there at Loading fixtures.... indefinately

**Comment by rande** [comment]
@redactuk ok, weird, maybe you should report the issue to doctrine. I just add the ``--no-interaction`` option to the load_data script. Thanks @DancZer and @redactuk

**Comment by redactuk** [comment]
@rande Regarding point 1, is reason Load Fixtures not running on main install due to error?

**Comment by rande** [comment]
@redactuk the load_data.php is the last command so I guess if one fail before the data are not loaded. Maybe we should move the load_data before mopa. https://github.com/sonata-project/sandbox/blob/2.4-develop/composer.json#L121-L124

**Comment by redactuk** [comment]
ok thaks. final quick question: want me to open separate open issue for depreciation/warnings reported in logs on this demo version or are these already know about?

**Comment by rande** [comment]
The deprecating issues is being removed, but this is a long process, no need to opening issues. You can however open PR to fix them ;)

**Comment by DancZer** [comment]
doctrine waiting for confirmation:
Careful, database will be purged. Do you want to continue Y/N ?

It take me some time to find out why i can't load data. I'm glad that i save some of your time  @redactuk  :)

**Comment by redactuk** [comment]
@DancZer Thanks. I'm going to be spending a lot of time with Sonata over the coming year so I will do my best to provide as much testing/feedback as I can :)
