### ISSUE TITLE
Incorrect demobundle logo src paths

### ISSUE THREAD

**Issue by redactuk** [sonata-project/sandbox#526]
Minor issue: when viewing Demo Bundles page paths to logos don't resolve. seems to be via:
\src\Sonata\Bundle\DemoBundle\DataFixtures\ORM\LoadPageData.php

**Comment by jordisala1991** [comment]
I just visited that php file, to check if there are broken images and couldnt find any: https://github.com/sonata-project/sandbox/blob/3.0/src/Sonata/Bundle/DemoBundle/DataFixtures/ORM/LoadPageData.php#L633

Closing for now, please use 3.0 branch and if you find any issue with images, please open another issue.
