### ISSUE TITLE
which version installed on: http://demo.sonata-project.org/

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/sandbox#527]
i have some errors with 2.3, 2.3-develop.... :(

**Comment by rande** [comment]
It is the 2.4-develop

**Comment by OskarStark** [comment]
ok, but the compsoer command isn't working:

![bildschirmfoto 2015-06-22 um 14 24 40](https://cloud.githubusercontent.com/assets/995707/8281657/8024d910-18ea-11e5-9d06-8258f7260c2f.png)

**Comment by OskarStark** [comment]
and shouldntt we make this branch the default branch here @github?

**Comment by OskarStark** [comment]
This one is working: composer create-project sonata-project/sandbox:dev-2.4-develop

shall i fix the README?
