### ISSUE TITLE
Twitter block isn't working on windows dev server

### ISSUE THREAD

**Issue by silver619** [sonata-project/sandbox#530]
The twitter widget isn't coming up only the link is there a particular php extension that is required for it to function?

**Comment by Soullivaneuh** [comment]
@silver619 Can you provide screenshots and error logs if you have?

**Comment by silver619** [comment]
I am not getting any errors. None for apache, php or in the app/logs folder. I have attached a screenshot.

![sonata-twitter](https://cloud.githubusercontent.com/assets/10975077/8373840/4fcb3100-1c01-11e5-8a49-20eb77afc484.jpg)

**Comment by Soullivaneuh** [comment]
Maybe do you have logs on browser debugger?

**Comment by silver619** [comment]
i get two but they are related to facebook, get the same ones on a linux dev server as well where the widget actually works. They are below, and they are in the script all.js on line:64

- Invalid App Id: Must be a number or numeric string representing the application id.
- FB.getLoginStatus() called before calling FB.init().

**Comment by silver619** [comment]
I am using easyphp dev server 14.1 on windows 8.1. Just in case you might need that info.

**Comment by jordisala1991** [comment]
This looks more related to the https://github.com/sonata-project/SonataSeoBundle

Closing as this issue is too old and probably fixed. My guess is that you need curl extension, but cant be sure.

**Comment by Xymanek** [comment]
> too old and probably fixed

It isn't - hence why I commented it out on 3.0:

https://github.com/sonata-project/sandbox/blob/bd8eeab5ddda35041b96a7b41a37aa1b3bddc798/src/Sonata/Bundle/DemoBundle/DataFixtures/ORM/LoadPageData.php#L351-L358

**Comment by jordisala1991** [comment]
But it is still related to SeoBundle, care to opening an issue there?

**Comment by Xymanek** [comment]
Done: https://github.com/sonata-project/SonataSeoBundle/issues/270

P.S. sorry for quick job of filling the issue
