### ISSUE TITLE
Children Page (core) block not working

### ISSUE THREAD

**Issue by moonraking** [sonata-project/sandbox#534]
Adding a Children Page (core) to any page seems to render nothing but the Blocks title.

Add a Children Page to the Top container for instance to the live demo.
Set the Current check box on.  This renders nothing.
Set the Current check box off and select the Homepage as the PageId. This renders the title but no child pages.

On my dev environment I get the following error

```
An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'Route 'sonata_page_bundle_inner_controller' not found' not found") in SonataPageBundle:Block:block_core_children_pages.html.twig at line 21. 
```

What am i missing?

**Comment by jordisala1991** [comment]
This issue is really old. If it is still happening on master branch you should reopen the issue on the appropriate sonata bundle (SonataPageBundle) in this case
