### ISSUE TITLE
Cant get sonata project to install

### ISSUE THREAD

**Issue by shairyar** [sonata-project/sandbox#536]
While installing Sonata Project (COMPOSER INSTALLATION)

<pre>
<code>
composer create-project sonata-project/sandbox:dev-2.4-develop
</pre>

</code>
I get the following error

<pre>
<code>
Installing sonata-project/sandbox (dev-2.4-develop 7af09447cf4417d8d452dbdff92ffea816898cb8)
  - Installing sonata-project/sandbox (dev-2.4-develop 2.4-develop)
    Cloning 2.4-develop

Created project in /opt/lampp/htdocs/sandbox
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-migrations-bundle ~2.0@dev -> satisfiable by doctrine/doctrine-migrations-bundle[2.0.x-dev].
    - doctrine/doctrine-migrations-bundle 2.0.x-dev requires symfony/symfony >=2.0,<2.1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see  for more details.

Read  for further common problems.
</pre>

</code>

I am not able to move beyond this problem. I have looked into the following issues and gone through their recommendation but still i cant get it to work

https://github.com/sonata-project/sandbox/issues/298
https://github.com/sonata-project/sandbox/issues/327

**Comment by Martin1982** [comment]
I've been having issues with this as well it seems like the dependency doesn't exist anymore. This is often why 'dev' references aren't recommended.

**Comment by davask** [comment]
Hi guys,

here a [workable solution](https://github.com/sonata-project/sandbox/issues/561#issuecomment-258381344) of sandbox

**Comment by jordisala1991** [comment]
Please use 3.0 branch.

Related to #602 

Closing
