### ISSUE TITLE
Schema creation error   php app/console doctrine:schema:create

### ISSUE THREAD

**Issue by sarathraj-coder** [sonata-project/sandbox#538]
I tried doctrine 2.4 and 2.5 but getting same error , any solution for below error 

[Doctrine\ORM\Mapping\MappingException]  
  Entity 'Sonata\Bundle\DemoBundle\Entity\Car' has to be part of the discriminator map of 'Sonata\Bundle\DemoBundle\E  
  ntity\Car' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Sonata\Bundle\DemoBundle  
  \Entity\Car' an abstract class to avoid this exception from occurring.

**Comment by jordisala1991** [comment]
Old issue. Feel free to check again with master branch
