### ISSUE TITLE
can not upload image on sonata-demo website

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/sandbox#543]
can you please check that? @rande

**Comment by rande** [comment]
no. The demo is being rework with a new infrastructure.

**Comment by OskarStark** [comment]
ok

**Comment by rande** [comment]
@OskarStark please see http://demo.sonata-project.org ;) Feedbacks  are welcome

**Comment by OskarStark** [comment]
![bildschirmfoto 2015-08-25 um 17 59 26](https://cloud.githubusercontent.com/assets/995707/9472007/30b9fe82-4b53-11e5-91a0-4143b85b82f9.png)

pixlr isn't working :)

upload works fine!

**Comment by OskarStark** [comment]
otherwise you should deactivate the pixlr button @rande
