### ISSUE TITLE
Allowed memory size on loading data

### ISSUE THREAD

**Issue by tophsic** [sonata-project/sandbox#547]
I run my Symfony and Sonata projects in a Docker environment with php-fpm. By default, `memory_size` of PHP scripts is set to 128M.

I tried the [quick installation](https://github.com/sonata-project/sandbox#quick-installation).

As I load data, I got:

```shell
Resetting demo
Executing :  rm -rf ./app/cache/*

Executing :  /usr/local/bin/php ./app/console cache:create-cache-class --env=prod --no-debug

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /home/httpd/educotel/app/bootstrap.php.cache on line 2675
```

I wanted to warmup sandbox quickly so I just used options `-d memory_limit=1024M -d max_execution_time=600` for each commands and it is great.

Do not know if it is really necessary to fix this in `bin/load_data.php` script.

**Comment by Soullivaneuh** [comment]
> Do not know if it is really necessary to fix this in bin/load_data.php script.

Nope. Memory limit should be configured on you php.ini.

**Comment by rande** [comment]
@Soullivaneuh for the record, the 2.4-develop contains fix with increase memory limit: https://github.com/sonata-project/sandbox/blob/2.4-develop/bin/load_data.php#L98

**Comment by Soullivaneuh** [comment]
@rande Hmm... Note sure it's the proper solution. :-)

**Comment by rande** [comment]
We need a n00b proof solution ;)

**Comment by rande** [comment]
No offense to @tophsic I am also running cli with a 128Mb limit ;)

**Comment by Soullivaneuh** [comment]
Well...

![3 monkeys 3](https://cloud.githubusercontent.com/assets/1698357/9818199/894891c4-58a7-11e5-9c3d-b72356d860f9.jpg)

**Comment by tophsic** [comment]
Indeed @rande I did notre try on branch 2.4! Thanks
