### ISSUE TITLE
Introduction + a few ideas

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/sandbox#548]
Hey there,

My name is Márk Sági-Kazár, a PHP developer from Hungary. I've already sent a few PRs, mainly with translations. I played with sonata in the last few weeks, and I am pretty impressed.

Currently my choice of framework is FuelPHP, but soon I will have to move to symfony, because it is the framework of choice at my new work. For FuelPHP I started a project with my friend, called IndigoPHP which is 100% the same as Sonata. In the last few months we couldn't spend as much time with Indigo as we wanted, also we will have to use Symfony, so I think we will abandon that project and work on Sonata instead. If you have any roadmap I would be happy to help with it.

For now, I have a few ideas for the sandbox:
1. As I can see the project's symfony files are not updated with the symfony version. Some .htaccess files are from 2.1, etc. It would be good to update them.
2. I am not sure if it is on purpose, but the logs and cache folders are removed which are - as far as I know - recommended to be there to ease installation. The contents olf these folders should be ignored though, this can be done with a simple .gitkeep file
3. 2.4 branch alias still says 2.3
4. the bin directory is reserved for composer package "binaries". At least I don't find it nice that symlinks are version controlled. Project specific scripts might be moved to a scripts folder, so that bin can be removed and ignored
5. For requirements check: the symfony requirements check requires vendor libraries to be installed. I think this means, that for checking further dependencies LiipMonitorBundle could be used. Also, if the extensions checked in sonata-check.php are hard dependencies, they could even be required in the composer file, so the installation itself fails. If they are not hard dependencies, LiipMonitorBundle could be configured to check. I am not sure though if it worths the extra dependency.
6. A big part of the load data script invokes other console commands. It could be split into two separate files: one which containes the rest of PHP codes and an other, which is a schell script. Actually the load data script could also be a symfony command in the AppBundle
7. Also about the load data script: in case the database user is not root, it is unlikely that the MySQL user has access to drop the database. I would add a --drop-schema option (this could work, if the script was a symfony command) so that instead of dropping the whole database, the script only drops the schema.

If you find any of the upper useful, I would be happy to provide PRs.

**Comment by sagikazarmark** [comment]
Ping @rande

**Comment by OskarStark** [comment]
@sagikazarmark i like your ideas.

can you please open this ticket in the SonataAdminBundle, i think its the most used bundle and should be the center point!

**Comment by sagikazarmark** [comment]
Sure, although most of my ideas are related to the sandbox.

**Comment by OskarStark** [comment]
you are right, we keep the sandbox related things here in this ticket.

**Comment by sagikazarmark** [comment]
Should I open separate tickets for the ideas mentioned? IMO It's enough to let me know which you would like to see implemented and I will open separate PRs for them.

**Comment by OskarStark** [comment]
@sagikazarmark i switched to a numberd ordered list for refering.

1. :+1: 
2. @rande i'm not sure if this is necessary for the docker setup or anything else
6. :+1: 
7. :+1:

**Comment by sagikazarmark** [comment]
:+1: 

Option two helps when someone wants to start a project based on the sandbox.

What about 5-7?

**Comment by OskarStark** [comment]
updated my post, sorry if you use:

```
1.
2.
6.
7.
```

github creates:
```
1.
2.
3.
4.
```

strange...
the other parts are IMO not so important, so lets check the other points by someone else

**Comment by sagikazarmark** [comment]
Yeah, I also hate this reordering. Will look into the mentioned points.

About the "skipped" points:

As said, having caching directories in the repo makes creating projects from sandbox easier.

Removing the bin directory removes errors during composer install, like `Skipped installation of bin phpunit for package phpunit/phpunit: name conflicts with an existing file`. These are symlinks actually which has nothing to do in the repository.

**Comment by jordisala1991** [comment]
This issue is really old, not sure if anything applies anymore, feel free to open more issues based on the master branch
