### ISSUE TITLE
Wrong repository class

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/sandbox#549]
Post has a dedicated repository, but in the metadata it is set to the default entity repository:

https://github.com/sonata-project/sandbox/blob/2.4-develop/src/AppBundle/Resources/config/doctrine/News.Post.orm.xml#L14

**Comment by jordisala1991** [comment]
Simply use this skeleton to fix the issue: https://github.com/sonata-project/SonataNewsBundle/blob/3.x/src/Resources/config/doctrine/Post.orm.xml.skeleton

**Comment by jordisala1991** [comment]
Old issue without answer
