### ISSUE TITLE
Database parameters

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/sandbox#550]
For some reasons the sandbox project uses dot notation in database parameters: `database.driver`. However the symfony standard is `database_driver`. Changing this is a BC break, however running composer install would simply ask these details again. Should I change this to the standard?

**Comment by OskarStark** [comment]
:+1:  for standard.

i think we don't need BC in the sandbox IMO

what do you guys think? @rande @Soullivaneuh

**Comment by rande** [comment]
Go for it, don't worry about bc break at it is the main entry point. Nobody will update the sandbox on a running project.

**Comment by sagikazarmark** [comment]
Implemented it in the symfony actualization PR.

**Comment by jordisala1991** [comment]
Fixed in your own PR: https://github.com/sonata-project/sandbox/pull/551

This is also on the 3.0 branch (new)

Closing
