### ISSUE TITLE
Minimal PHP version

### ISSUE THREAD

**Issue by zajca** [sonata-project/sandbox#571]
Hi, 
I run to this issue when installing.
```
composer create-project sonata-project/sandbox:2.3.x-dev

PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /<path>/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 98
```
package-versions is using php7 syntax and will throw error on php <7

**Comment by OskarStark** [comment]
Can you please provide a PR?

**Comment by zajca** [comment]
Well I'm not sure where the problem is and how to fix it. Not even sure what package depends on package-versions. Easy way to fix this would be require minimum php7, but I'm not sure if it's desired :)

**Comment by jjborie** [comment]
Be careful, tried with php 7 couple weeks ago wasn't working but work perfectly with last version of hhvm and it's very fast.

**Comment by khal3d** [comment]
`ocramius/package-versions` is required by `doctrine/doctrine-migrations-bundle`. I have the same issue on my own Symfony project _(I'm not using Sonata)_ and I can't install `doctrine/doctrine-migrations-bundle` anymore because of this.

**Comment by Soullivaneuh** [comment]
`ocramius/package-versions` is a PHP7 only package. If you use `--ignore-platform-reqs`, indeed you take the risk to have not wanted strange behavior.

This issue is not related to Sonata, closing.
