### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/sandbox#576]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/admin-bundle ~2.4@dev -> satisfiable by sonata-project/admin-bundle[2.4.x-dev].
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle 3.x-dev@dev -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - remove sonata-project/doctrine-orm-admin-bundle 2.4.x-dev|keep sonata-project/doctrine-orm-admin-bundle dev-master
    - Can only install one of: sonata-project/admin-bundle[3.x-dev, 2.4.x-dev].
    - Installation request for sonata-project/doctrine-orm-admin-bundle ~2.4@dev -> satisfiable by sonata-project/doctrine-orm-admin-bundle[2.4.x-dev].

**Comment by mgomez-dgt** [comment]
same error help please!

**Comment by davask** [comment]
Hi guys,

here a [workable solution](https://github.com/sonata-project/sandbox/issues/561#issuecomment-258381344) of sandbox

**Comment by greg0ire** [comment]
Closing because of #583
