### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Yoann-TYT** [sonata-project/sandbox#580]
When i launch composer create-project sonata-project/sandbox:2.3.x-dev, I have got the following error :  

``
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package sonata-project/ecommerce dev-develop-deprecated exists as sonata-project/ecommerce[0.0.1, 1.0.0, 1.x-dev, 2.0.0, 2.x-dev, dev-master, 3.x-dev] but these are rejected by your constraint.
``

**Comment by krvajalmiguelangel** [comment]
I am facing the same issue. Any solution till now?

**Comment by lobodol** [comment]
Hi,
I've encountered the same issue doing a ```composer install````
Does anyone have a solution ?

**Comment by davask** [comment]
Hi guys,

here a [workable solution](https://github.com/sonata-project/sandbox/issues/561#issuecomment-258381344) of sandbox

**Comment by codiiv** [comment]
@davask That  "workable" solution is not workable :)

**Comment by davask** [comment]
That s weird, it works fine for me.

What is your lamp stack ?

**Comment by codiiv** [comment]
I am on Xampp actually

**Comment by davask** [comment]
Have you ever think to use docker instead ?

**Comment by greg0ire** [comment]
docker with nginx - php-fpm - postgres FTW!

**Comment by davask** [comment]
I prefer apache 2.4 and MySql but I m pretty classic in techno choices ;)

**Comment by greg0ire** [comment]
Whatever works :)

**Comment by greg0ire** [comment]
Closing because of #583
