### ISSUE TITLE
sonata page composer in front : how to enable it

### ISSUE THREAD

**Issue by davask** [sonata-project/sandbox#584]
Hi,

I spend some time between guideline and own debugging to active this 

SonataPageBundle::base_layout.html.twig l.56 > 66 

```html
                <!-- CMS specific variables -->
                <script>
                    jQuery(document).ready(function() {
                        Sonata.Page.init({
                            url: {
                                block_save_position: '{{ sonata_admin.objectUrl('sonata.page.admin.page', 'edit', page) }}',
                                block_edit:          '{{ sonata_admin.url('sonata.page.admin.page|sonata.page.admin.block', 'edit', {'id': 'BLOCK_ID'}) }}'
                            }
                        });
                    });
                </script>

```

SonataPageBundle::base_layout.html.twig l.71 > 76

```html
data-page-editor='{{ {
                    url: {
                        block_save_position: sonata_admin.objectUrl('sonata.page.admin.page', 'edit', page),
                        block_edit:          sonata_admin.url('sonata.page.admin.page|sonata.page.admin.block', 'edit', {'id': 'BLOCK_ID'})
                    }
                }|json_encode()|raw }}'
```

However it doesn t work.

I m not able to bring the js Object Sonata.Page and I have an exception as follow : 

```php
An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("childId") to generate a URL for route "admin_app_page_page_page_block_edit".") in SonataPageBundle::base_layout.html.twig at line 62.
```

Can you help ?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

**Comment by davask** [comment]
I can t find usefull documentation on that topic.

**Comment by kptLucek** [comment]
Sorry for reopening, but im facinig similar issue right now.

Things i've done:
- Installed & configured fresh version of symfony (4.3 atm)
- installed & configured SonataAdmin, SonataDoctrineAdmin, SonataPage
- i have set:
```
sonata_page:
    is_inline_edition_on: true
```

My user has edit permissions on page

Error: 

**An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("childId") to generate a URL for route "admin_app_sonatapagepage_sonatapageblock_edit".").** 

i did not perform any changes on templates, code and others, as mentioned above - fresh install & also were searching on documentation [here](https://sonata-project.org/bundles/page/master/doc/reference/installation.html)

Thanks in advance

**Comment by thomasBourdin** [comment]
Hi,

I have found that there is some errors in the sonata page default base_layout.
I have corrected this by copy this file, and save it in my project directory templates, and use this new file as base layout.
if you locate this file in /template/Layouts/base_layout.html.twig extend your template as follow : 
{% extends '/Layouts/base_layout.html.twig' %}

Then, change the url for the editon block from 
`  block_edit:          sonata_admin.url('sonata.page.admin.page|sonata.page.admin.block', 'edit', {'id': 'BLOCK_ID'})`  
to
`  block_edit:          sonata_admin.url('sonata.page.admin.page|sonata.page.admin.block', 'edit', {'id': page.id , 'childId': 'BLOCK_ID'})`  
This will let you jump to the admin edition page when you double click to the block.


You will also need to add the jquery UI lib in header (i use the pixsortable file but you can use the one you want).

`  
 {% for js in sonata_page.assets.javascripts %}
                        <script src="{{ asset(js) }}"></script>
 {% endfor %}
{# Add this line #}
                    <script src="/bundles/pixsortablebehavior/js/jquery-ui.min.js"></script>

`
