### ISSUE TITLE
how to find not existing controller::action for route?

### ISSUE THREAD

**Issue by sruj** [sonata-project/sandbox#588]
Symfony profiler says url `/admin/app/page-page/9/edit` matches route `admin_app_page_page_edit` that open `PageAdminController :: editAction` but i dont see any `editAction` in `PageAdminController`.  

(Please answer before closing. I'm trying to figure it out for hours) (stackoverflow will ignore this question)

**Comment by core23** [comment]
Sorry, we try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

We don't have time either to answer ALL questions. StackOverflow is a better place for all users.

Habe a look at the class inheritance, this would solve your question.

**Comment by sruj** [comment]
damn, i'm idiot.
