### ISSUE TITLE
Sonata comment bundle threads

### ISSUE THREAD

**Issue by famas23** [sonata-project/sandbox#589]
I'm working in sonata sandbox , it seems that by default the comment threads is not configured , so can some one explain how to show comment threads with sonata comment bundle .

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
