### ISSUE TITLE
Unable to add block container in global composer

### ISSUE THREAD

**Issue by davask** [sonata-project/sandbox#590]
Hi,

I m trying to allow admin to add block container within a block container like in the footer of the global page on sonata demo, but it doesn t work.

The block is created without parent assignment, when I refresh the composer zone for the footer block i got this ajax response

"No parent found, unable to preview an orphan block"

In the same topic, when I try to add a block to an empty block container through this url /admin/core/append-form-field-element?code=sonata.page.admin.block&elementId=s582267c897d8c_children&objectId=95&uniqid=s582267c897d8c

I got this error 

"The block service `` does not exist"

How can I fix it ?

**Comment by davask** [comment]
Another example is this error : Admin service "sonata.block.service.container" not found in admin pool.

**Comment by davask** [comment]
I found a way to add block container for administration but so far I have to override some files in the vendor/sonata-project/admin-bundle, vendor/sonata-project/block-bundle & vendor/sonata-project/page-bundle directories.

I had to override the vendor/sonata-project/admin-bundle/Admin/Pool.php which is called in a lots of files within the different bundles from the sonata project and I can t simply override it (except misunderstanding on my side).

What can I do to make it more sonata friendly ?

Below the files involved in my overriding

![sonota-block-admin](https://cloud.githubusercontent.com/assets/482210/20275800/1a4a4434-aa9a-11e6-970b-ea1a4b7b2377.png)

**Comment by OskarStark** [comment]
Can you provide this as a PR, its much easier to "talk" about code.

Thank you @davask 👍

**Comment by davask** [comment]
How do you want me to do that as my modifications are in the vendor directory it is ignored from any commit.
I could make a PR per bundle but we will loose the overall view as my modifications are across bundles.

Otherwise I can push in src the files with respected tree structure but that will not be best practices.

Whta is you suggestion @OskarStark ?

**Comment by OskarStark** [comment]
Puh, you are right, any idea @greg0ire ?

**Comment by greg0ire** [comment]
Uuuuh… something like this : 

```
for vendor in some/vendor some/othervendor
do
pushd vendor/$vendor
git --no-pager diff
popd
done
```

You can list modified vendor with `composer status`

**Comment by davask** [comment]
Thanks @greg0ire, 

However, the admin-bundle and block-bundle have no .git repository (How is it possible ?) and the composer status return a git diff.

**Do you want a git diff file or a PR ?**

About admin-bundle and block-bundle, I m using : 
- "sonata-project/admin-bundle": "~3.9"
- "sonata-project/block-bundle": "~3.2"

do I _git init && git fetch_ https://github.com/sonata-project/SonataAdminBundle/tree/3.x
and https://github.com/sonata-project/SonataBlockBundle/tree/3.x to comply with your bash script ?

**Comment by greg0ire** [comment]
> the admin-bundle and block-bundle have no .git repository (How is it possible ?)

It happens when composer chooses to install from a tarball instead of a git, which is the default for stable versions AFAIK

So basically, you can't have a diff, sorry… unless you reinstall composer with `--prefer-source` (I think), and then copy your changes again over that.

> Do you want a git diff file or a PR ?

I don't think you can make a PR, you can only make several of them… so `git diff` it is.

**Comment by davask** [comment]
Below the result from greg0ire script : 

```bash

~/files/vendor/sonata-project/admin-bundle ~/files
diff --git a/Admin/Pool.php b/Admin/Pool.php
index 63856d2..d8f69e8 100644
--- a/Admin/Pool.php
+++ b/Admin/Pool.php
@@ -194,6 +194,9 @@ class Pool
         }

         if (count($this->adminClasses[$class]) > 1) {
+            if (in_array($class, array("Sonata\PageBundle\Entity\Block","Application\Sonata\PageBundle\Entity\Block","AppBundle\Entity\Page\Block"))) {
+                return $this->getInstance("sonata.page.admin.block");
+            }
             throw new \RuntimeException(sprintf('Unable to find a valid admin for the class: %s, there are too many registered: %s', $class, implode(',', $this->adminClasses[$class])));
         }

~/files
~/files/vendor/sonata-project/block-bundle ~/files
diff --git a/Block/Service/ContainerBlockService.php b/Block/Service/ContainerBlockService.php
index 71efcce..2502a2c 100644
--- a/Block/Service/ContainerBlockService.php
+++ b/Block/Service/ContainerBlockService.php
@@ -31,6 +31,8 @@ class ContainerBlockService extends AbstractAdminBlockService
     public function buildEditForm(FormMapper $formMapper, BlockInterface $block)
     {
         $formMapper->add('enabled');
+        $formMapper->add('page');
+        $formMapper->add('parent');

         $formMapper->add('settings', 'sonata_type_immutable_array', array(
             'keys' => array(
@@ -41,12 +43,14 @@ class ContainerBlockService extends AbstractAdminBlockService
             ),
         ));

-        $formMapper->add('children', 'sonata_type_collection', array(), array(
-            'admin_code' => 'sonata.page.admin.block',
-            'edit' => 'inline',
-            'inline' => 'table',
-            'sortable' => 'position',
-        ));
+        if(!in_array($block->getType(), array("sonata.page.block.container", "sonata.block.service.container"))) {
+            $formMapper->add('children', 'sonata_type_collection', array(), array(
+                'admin_code' => 'sonata.page.admin.block',
+                'edit' => 'inline',
+                'inline' => 'table',
+                'sortable' => 'position',
+            ));
+        }
     }

     /**
~/files
~/files/vendor/sonata-project/page-bundle ~/files
diff --git a/Admin/BaseBlockAdmin.php b/Admin/BaseBlockAdmin.php
index d3fbc74..b54188f 100644
--- a/Admin/BaseBlockAdmin.php
+++ b/Admin/BaseBlockAdmin.php
@@ -71,6 +71,10 @@ abstract class BaseBlockAdmin extends AbstractAdmin
     {
         $block = parent::getNewInstance();
         $block->setType($this->getPersistentParameter('type'));
+        if(is_null($block->getType())) {
+            $block->setType('sonata.page.block.container');
+
+        }

         return $this->loadBlockDefaults($block);
     }
diff --git a/Admin/BlockAdmin.php b/Admin/BlockAdmin.php
index ce37f78..71b21a0 100644
--- a/Admin/BlockAdmin.php
+++ b/Admin/BlockAdmin.php
@@ -137,7 +137,8 @@ class BlockAdmin extends BaseBlockAdmin
         $formMapper->end();

         $isContainerRoot = $block && in_array($blockType, array('sonata.page.block.container', 'sonata.block.service.container')) && !$this->hasParentFieldDescription();
-        $isStandardBlock = $block && !in_array($blockType, array('sonata.page.block.container', 'sonata.block.service.container')) && !$this->hasParentFieldDescription();
+        // $isStandardBlock = $block && !in_array($blockType, array('sonata.page.block.container', 'sonata.block.service.container')) && !$this->hasParentFieldDescription();
+        $isStandardBlock = true;

         if ($isContainerRoot || $isStandardBlock) {
             $formMapper->with('form.field_group_general', $generalGroupOptions);
@@ -209,6 +210,7 @@ class BlockAdmin extends BaseBlockAdmin
                 ->with('form.field_group_options', $optionsGroupOptions)
                 ->add('type', 'sonata_block_service_choice', array(
                         'context' => 'sonata_page_bundle',
+                        'include_containers' => true,
                     ))
                 ->add('enabled')
                 ->add('position', 'integer')
diff --git a/Controller/BlockAdminController.php b/Controller/BlockAdminController.php
index eb6febd..4236a4a 100644
--- a/Controller/BlockAdminController.php
+++ b/Controller/BlockAdminController.php
@@ -88,7 +88,7 @@ class BlockAdminController extends Controller

         if (!$parameters['type']) {
             return $this->render('SonataPageBundle:BlockAdmin:select_type.html.twig', array(
-                'services' => $this->get('sonata.block.manager')->getServicesByContext('sonata_page_bundle'),
+                'services' => $this->get('sonata.block.manager')->getServicesByContext('sonata_page_bundle', true),
                 'base_template' => $this->getBaseTemplate(),
                 'admin' => $this->admin,
                 'action' => 'create',
@@ -154,7 +154,7 @@ class BlockAdminController extends Controller
             throw new PageNotFoundException('No parent found, unable to preview an orphan block');
         }

-        $blockServices = $this->get('sonata.block.manager')->getServicesByContext('sonata_page_bundle', false);
+        $blockServices = $this->get('sonata.block.manager')->getServicesByContext('sonata_page_bundle', true);

         return $this->render('SonataPageBundle:BlockAdmin:compose_preview.html.twig', array(
             'container' => $container,
diff --git a/Controller/PageAdminController.php b/Controller/PageAdminController.php
index 688203f..d87059d 100644
--- a/Controller/PageAdminController.php
+++ b/Controller/PageAdminController.php
@@ -238,7 +238,7 @@ class PageAdminController extends Controller
             throw new NotFoundHttpException(sprintf('unable to find the block with id : %s', $id));
         }

-        $blockServices = $this->get('sonata.block.manager')->getServicesByContext('sonata_page_bundle', false);
+        $blockServices = $this->get('sonata.block.manager')->getServicesByContext('sonata_page_bundle', true);

         // filter service using the template configuration
         if ($page = $block->getPage()) {
diff --git a/Resources/views/Block/block_core_children_pages.html.twig b/Resources/views/Block/block_core_children_pages.html.twig
index 6840544..b62fb5b 100644
--- a/Resources/views/Block/block_core_children_pages.html.twig
+++ b/Resources/views/Block/block_core_children_pages.html.twig
@@ -18,7 +18,9 @@ file that was distributed with this source code.
         <ul class="sonata-page-menu-chilren-list">
             {% if page %}
                 {% for child in page.children %}
+                    {% if child.token is defined %}
                     <li class="sonata-page-menu-children-element"><a href="{{ path(child) }}" title="{{ child.name|escape }}">{{ child.name }}</a></li>
+                    {% endif %}
                 {% endfor %}
             {% endif %}
         </ul>
diff --git a/Resources/views/BlockAdmin/compose_preview.html.twig b/Resources/views/BlockAdmin/compose_preview.html.twig
index 7099ec8..6eebac9 100644
--- a/Resources/views/BlockAdmin/compose_preview.html.twig
+++ b/Resources/views/BlockAdmin/compose_preview.html.twig
@@ -9,6 +9,7 @@
     >
         {% set service = attribute(blockServices, child.type) %}
         <h4 class="page-composer__container__child__name">{{ child.name|default(service.name) }}</h4>
+        <div>[#{{child.id}}]</div>
         {% if not service.blockMetadata.image %}
             <i class="{{ service.blockMetadata.option('class') }}" ></i>
         {% else %}
~/files

```

**Comment by greg0ire** [comment]
The first diff references the block bundle, we're never going to merge this. You may disambiguise by providing the `admin_code`.

**Comment by davask** [comment]
What do you mean by _providing the ```admin_code```_ ?

**Comment by greg0ire** [comment]
Here is some documentation about it : https://github.com/sonata-project/SonataAdminBundle/blob/240ecbd02d453f9acaf81e00112ff5d8dae4459b/Resources/doc/reference/form_types.rst#fielddescription-options

**Comment by davask** [comment]
Thanks for that !

What about overriding the vendor/sonata-project/admin-bundle/Admin/Pool.php in src/Application/Sonata/AdminBundle/Admin/Pool.php ? 

The overriding doesn't work as **use Sonata\AdminBundle\Admin\Pool** is called in lots of vendor/sonata-project/*.

Is there s a way to tell symfony to identify src/Application/Sonata/AdminBundle as Sonata\AdminBundle\Admin\Pool and if a file is missing in src/Application/Sonata/AdminBundle then it check in vendor/sonata-project/admin-bundle ?

Or Am I missing something ?

FYI : I m not trying to override sonata bundles through some AppBundle but through Application\Sonata, as far as I know it doesn t matter, but I just wanted to mention it.

**Comment by greg0ire** [comment]
Well you can fork the bundles if you want to override, and use inline-aliases to refer to your fork(s). Once it works, consider contributing your fixes back.

**Comment by davask** [comment]
Okay, I ll try to do that and get back to you. It might take some time as I m less advanced than you on symfony.
Thanks for the help

**Comment by greg0ire** [comment]
No problem, keep up with the positive attitude, here is how you can use your forks in case you're wondering : https://getcomposer.org/doc/articles/aliases.md#require-inline-alias

**Comment by davask** [comment]
I got one more question before digging, Why did you (as sonata project) not allow to manage 'sonata.page.block.container' and 'sonata.block.service.container' through the admin but put some of them in the demo ?

Is there a reason am I missing ?

**Comment by greg0ire** [comment]
I don't understand your question.

**Comment by davask** [comment]
Why is the 'sonata.page.block.container' block is not available by default in the _pageAdmin compose_ ?

**Comment by greg0ire** [comment]
I really don't know, I don't use the page bundle. @OskarStark , do you know?

**Comment by ebrost** [comment]
really interested by this feature. I did @davask steps and i can add a block container but can't put any child in it

**Comment by davask** [comment]
@ebrost, it is a tricky feature, I haven t fix it yet, and I will not be able to do so before a few months unfortunatly.
Some times, you have to create an independant block, through the block admin. Once created, you can add a child to a parent. this is definitly not perfect and not prod ready but it is a start.

However if @OskarStark, can help us on the purpose of not having this feature by default, I ll be interested to know why before suggesting a PR for this feature.

**Comment by ebrost** [comment]
yes, it's tricky indeed, specially the part in Pool.php, but you're right, this feature should be available by default. As i'm a newbie on Symfony and Sonata, i'm not able to do a PR by myself. I will wait ....

**Comment by mrpdean** [comment]
Yes, facing the same bug too.
