### ISSUE TITLE
Menu block doesn t show class options

### ISSUE THREAD

**Issue by davask** [sonata-project/sandbox#593]
I m trying to setup the menu block added through the _admin compose_ and the menu class - for instance - doesn t show up in the html code.

How can I fix that ?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
