### ISSUE TITLE
'sonata_formatter_type' does not initially selects proper content format

### ISSUE THREAD

**Issue by TheCelavi** [sonata-project/sandbox#596]
Description: SonataNewsBundle uses 'sonata_formatter_type' for content field. When you save content with any other format, on edit, saved format is not selected.

Steps to reproduce a bug:

1. Go to sonata demo http://demo.sonata-project.org/ and create container, login into administration, go to dashboard (backend), path:  [domain]/admin/app/news-post/list
2. Open any news post for editing
3. Edit content by changing formatting type for field Content to, per  example "richhtml"
4. Click "Update" button

Expected result: Content is saved with new formatter, formatter is initially selected, CK editor is displayed on load.

Actual result: HTML code is displayed in Textarea, "markdown" content formatter is selected.

**Comment by jordisala1991** [comment]
Duplicated of another issue, and fixed by: https://github.com/sonata-project/SonataFormatterBundle/pull/308

Closing
