### ISSUE TITLE
Route 'admin_sonata_page_page_create' not found

### ISSUE THREAD

**Issue by TheCelavi** [sonata-project/sandbox#597]
Steps to reproduce bug:

- Create demo container (it can be reproduced on demo, demo.sonata-project.org) 
- Go to any page that does not exists, example: /app_dev.php/this-does-not-exists

You will have message displayed that route can not be found.

**Comment by coudenysj** [comment]
See https://github.com/sonata-project/SonataPageBundle/issues/493.

**Comment by OskarStark** [comment]
Thanks @coudenysj 👍 

This is fixed in sonata-project/SonataPageBundle#777
