### ISSUE TITLE
LoadNewsData of load_data

### ISSUE THREAD

**Issue by Bayansuren** [sonata-project/sandbox#600]

**Comment by greg0ire** [comment]
Dude, seriously?

**Comment by Bayansuren** [comment]
LOL, When I launch php_load, Its showed me and suggested to post in the here. Thats why I posted here. I am newbie in Sandbox. If you know this error, Could you post something?.

**Comment by greg0ire** [comment]
Well it's one thing to be "a newbie in Sandbox", but it's another to be a newbie at asking a question properly. You posted a stack trace, great, but didn't you get an error message before it? If yes, you should definitely provide it too.

Also, you should learn about github flavored markdown, and how it can help you make your message a bit more readable.

**Comment by Bayansuren** [comment]
Your correct. It was my bad. I never faced like this error before. Finally whats the error?.

**Comment by greg0ire** [comment]
![poyjgmt](https://cloud.githubusercontent.com/assets/657779/24740862/8638f3a6-1aa3-11e7-9386-5f93a3a2167c.gif)
