### ISSUE TITLE
How can i add web navigation bar like on demo: 

### ISSUE THREAD

**Issue by GothicBezimienny** [sonata-project/sandbox#601]
Greetings, How can i add navigation bar like this ? : 

![image](https://cloud.githubusercontent.com/assets/26882446/25586259/d34abf1c-2e9e-11e7-94eb-0e60989df155.png)

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
