### ISSUE TITLE
There are any version working when downloading?

### ISSUE THREAD

**Issue by shawe** [sonata-project/sandbox#603]
Reading the README.rst all versions are not working as described. Based on packagist versions:

composer create-project sonata-project/sandbox:dev-master
composer create-project sonata-project/sandbox:2.3.x-dev
composer create-project sonata-project/sandbox:2.2.x-dev
composer create-project sonata-project/sandbox:2.1.x-dev
composer create-project sonata-project/sandbox:2.0.x-dev
composer create-project sonata-project/sandbox:dev-2.4-develop
composer create-project sonata-project/sandbox:dev-2.3-develop
composer create-project sonata-project/sandbox:dev-phpcr

All have problems like this:

Your requirements could not be resolved to an installable set of packages.

Any solution for try it offline?

**Comment by stefanlex90** [comment]
Still no fix :-1:

**Comment by jlamur** [comment]
Duplicate of #602
