### ISSUE TITLE
[Modernising] Handling of front end assets

### ISSUE THREAD

**Issue by Xymanek** [sonata-project/sandbox#607]
Currently sandbox uses php libraries to handle handle front end assets in a weird way:

- Bootstrap is downloaded using composer
- Bootstrap is symlinked post composer install/update **to a bundle**. THIS IS BROKEN ON WINDOWS as symlinks do not work unless script (composer in this case) is run as admin
- Bundles' assets are symlinked/copied to `web/bundles`
- These copied/symlinked files are then used by Assetic to generate its own files
- The last set of files is actually included for use in browser

This is rather convoluted and also depreciated:
![screenshot_3](https://user-images.githubusercontent.com/2865341/36341692-b94b784e-13fa-11e8-9dc8-e97557751b00.png)

Aaand broken (`sonata-sandbox/app_dev.php/admin/dashboard`):

![screen shot 2018-02-17 at 15 25 49-fullpage](https://user-images.githubusercontent.com/2865341/36341705-fe86eeb6-13fa-11e8-8885-2f96698221b1.png)
(With bootstrap step skipped)

![screen shot 2018-02-17 at 15 39 23-fullpage](https://user-images.githubusercontent.com/2865341/36341715-0aab0038-13fb-11e8-9ed5-8b1db461611e.png)
(Run composer as admin so everything is properly symlinked)

I think the correct way to handle this is to rework this whole thing to use webpack (via encore)

**Comment by VincentLanglet** [comment]
This project is abandoned
