### ISSUE TITLE
[Modernising] Cleanup branches

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/sandbox#610]
We have a lot of branches, and the new one is not the default.

We should decide which one is the default, IMO 3.0
And which ones we remove, IMO all except master.

We need to take care of how the website generates the demo, to not fuck up things tho :P

**Comment by VincentLanglet** [comment]
Let's clean this !

For what I understood
- 2.3 is the stable
- 3.0 was not production ready
- master was 5 year old

I removed 3.0 and replace the old master by the 3.0 branch.

Now
- 2.3 is the stable default branch
- master will be the next major release

I think I can close this then.
