### ISSUE TITLE
problem adding product in ecommerce - no object types available

### ISSUE THREAD

**Issue by simonspts** [sonata-project/sandbox#611]
I install sandbox without any problems, but there is a problem with adding sonata product. When I try to add new product it says No object types available. I have php 7.2 (ubuntu 16.04), and I try this also with php 5.6 and different branches 2.3, 2.4-develop an 3.0. Same error. Is this a bug or I have to install some special php modules or setup something?

**Comment by nicolasricci** [comment]
@simonspts this is linked to this issue https://github.com/sonata-project/ecommerce/issues/511
I have personnally restored the getClass() method in my overridden ProductAdmin to fix it.

**Comment by simonspts** [comment]
Thanks @nicolasricci, now it works. Why this method was removed if it doesn't work without it?

**Comment by SpectatoR51** [comment]
the same question!

**Comment by jordisala1991** [comment]
Linked issue is closed, this should belong to ecommerce, please reopen there if it is still present
