### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by filipe-carvalho** [sonata-project/sandbox#612]
Hello Dear Community :)

I am facing a problem installing the sandbox project im my local machine

By Documntation in said that should be done this steps:

1) curl -L github https://github.com/sonata-project/sandbox-build/archive/master.tar.gz | tar xzv
2) cp app/config/parameters.yml.dist app/config/parameters.yml

After that i make the composer update, however composer update fails in clearing cache with the following error

 You have to enable opcache.load_comments=1 or zend_optimizerplus.load_comments=1

I am doing something wrong or is some other problem ?
Thank you in advance

**Comment by greg0ire** [comment]
> You have to enable opcache.load_comments=1 or zend_optimizerplus.load_comments=1

This sounds like php configuration, make sure your php settings comply with this.

**Comment by filipe-carvalho** [comment]
@greg0ire Hello

I already changed my php configuration and added the enable of that modules, but still with no luck with the same error

**Comment by OskarStark** [comment]
Can you add a screencast?

filipe-carvalho <notifications@github.com> schrieb am Do. 8. Nov. 2018 um
10:02:

**Comment by jo66** [comment]
Hi there,

I had the same problem running `php bin/load_data.php` with php7.2, using php5.6 solved the problem but `composer update` still fails on doctrine-migrations-bundle:

> Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

> Problem 1
    - remove doctrine/doctrine-migrations-bundle 2.1.x-dev|keep doctrine/doctrine-migrations-bundle dev-master
    - doctrine/doctrine-migrations-bundle v2.0.0-beta1 requires php ^7.1 -> your PHP version (5.6.38) does not satisfy that requirement.
    - doctrine/doctrine-migrations-bundle v2.0.0-alpha1 requires php ^7.1 -> your PHP version (5.6.38) does not satisfy that requirement.
    - doctrine/doctrine-migrations-bundle 2.0.x-dev requires php ^7.1 -> your PHP version (5.6.38) does not satisfy that requirement.
    - doctrine/doctrine-migrations-bundle dev-master requires php ^7.1 -> your PHP version (5.6.38) does not satisfy that requirement.
    - Installation request for doctrine/doctrine-migrations-bundle ~2.0dev -> satisfiable by doctrine/doctrine-migrations-bundle[2.0.x-dev, v2.0.0-alpha1, v2.0.0-beta1, 2.1.x-dev].

More annoying, when running embedded server and browsing new installation of sandbox:

> An exception has been thrown during the rendering of a template ("Warning: array_key_exists(): The first argument should be either a string or an integer") in SonataProductBundle:Product:view_thumbnail.html.twig at line 38.

...

> CRITICAL - [cms::renderBlock] block.id=22 - error while rendering block - An exception has been thrown during the rendering of a template ("Warning: array_key_exists(): The first argument should be either a string or an integer") in "SonataProductBundle:Product:view_thumbnail.html.twig" at line 38. 
CRITICAL - [cms::renderBlock] block.id=18 - error while rendering block - An exception has been thrown during the rendering of a template ("Warning: array_key_exists(): The first argument should be either a string or an integer") in "SonataProductBundle:Product:view_thumbnail.html.twig" at line 38. 
CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Warning: array_key_exists(): The first argument should be either a string or an integer") in "SonataProductBundle:Product:view_thumbnail.html.twig" at line 38." at /home/jo66/www/sonata-sandbox/vendor/twig/twig/lib/Twig/Template.php line 304 

Steps to reproduce on Ubuntu 16.04 with php5.6:

1. Retrieve the code: `curl -L github https://github.com/sonata-project/sandbox-build/archive/master.tar.gz | tar xzv`
2. Rename folder: `mv sandbox-build-master sonata-sandbox`
3. Configure default the parameters.yml file: `cp app/config/parameters.yml.dist app/config/parameters.yml`
4. Load the data: `php bin/load_data.php`
5. Run `composer update` => produce error with with doctrine-migrations-bundle (see above)
6. Run `app/console server:run localhost:9090`
7. Browse [http://localhost:9090/](http://localhost:9090/) => produce exception (see above)

Can someone help with this?

Additionnaly, Sonata e-commerce bundle documentation says:

> In case you need to work with Sonata e-commerce for a new project or just want to test it for a simple overview, we strongly advise that you use our demo

But it seems demo is outdated so I guess better to start from scratch and use it as an example?
Maybe updated version of demo is planned?

**Comment by jordisala1991** [comment]
This issue is really old, can you try with master branch. Please open a new issue if necessary
