### ISSUE TITLE
install on PHP7

### ISSUE THREAD

**Issue by codeRemark** [sonata-project/sandbox#613]
I follow the install guide, also confirm database connection correctly( I think that should be), then run bellow command and got error as follows:

$ php bin/load_data.php
Resetting demo
Executing :  rm -rf ./app/cache/*

Executing :  /usr/bin/php ./app/console cache:warmup --env=prod --no-debug
Warming up the cache for the prod environment with debug false

Executing :  /usr/bin/php ./app/console cache:create-cache-class --env=prod --no-debug
Writing cache file ... done!

Executing :  /usr/bin/php ./app/console doctrine:database:drop --force

                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Warning: A non-numeric value encountered                   
                                                             

doctrine:database:drop [--connection[="..."]] [--if-exists] [--force]

An error occurs when running a command!

--------------------------------------

I googing the problem, but so far cannot solve it,  maybe cause the PHP 7 ??

also I see sandbox base symfony 2.5,   I want know if it upgrade to newest symfony 4   ? 

thanks

**Comment by codeRemark** [comment]
this demo is really confuse ...

in the composer.json : 

"sonata-project/ecommerce": "dev-develop-deprecated",

it point to a "deprecated" bundle, that is really confuse

**Comment by quisse** [comment]
Try composer create-project sonata-project/sandbox:3.0.x-dev for now

**Comment by jordisala1991** [comment]
I think this issue is solved, use master branch
