### ISSUE TITLE
Discussion about sandbox 4.0 

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/sandbox#621]
Hi, i want start discussion about new sandbox version, becouse 3.0 version is done (awaiting for merge). 

- [ ] upgrade Symfony to 4.4|5.0

**Comment by wbloszyk** [comment]
What do you think about:

- remove assetic and add webpack
- remove mopabootstrap
- update bootstrap to 4 version
- update or remove car part from demo
- update fixtures 
- update sonata bundles to the newest
    - SEOBundle
    - blockBundle
    - adminBundle
    - formatterBundle

@core23 Is PageBundle prepere to working with BlockBundle 4.x? You working on it.

**Comment by core23** [comment]
> @core23 Is PageBundle prepere to working with BlockBundle 4.x? You working on it.


AFAIK we need a new admin major release to add block support for (neraly) all bundles. 

// writing from my 📱

**Comment by OskarStark** [comment]
And we should finish webpack for admin bundle first

**Comment by wbloszyk** [comment]
I agree with finish next major for admin bundle. Some sonata bundles need update dependencies for using the newest version too. I wont create roadmap/milestones for 4.0 version becouse some work can be done before update admin bundle. I will help like with 3.0 version.

**Comment by VincentLanglet** [comment]
This project is abandoned
