### ISSUE TITLE
problem with doctrine:schema:update on 3.0 Branch

### ISSUE THREAD

**Issue by ayminovitch** [sonata-project/sandbox#622]
Hello Dear Community :)

Any solution for below error
![Capture](https://user-images.githubusercontent.com/6867464/75635400-10da4f80-5c16-11ea-8df1-d3e380575293.PNG)

`In RuntimeReflectionService.php line 75:
  Property AppBundle\Entity\Classification\Collection::$productCollection does not exist`

**Comment by wbloszyk** [comment]
@ayminovitch We know about it. It is ecommerce issue with mapping relation in SonataProductExtension.php. You can add this property without any methods, becouse IT is not used in code.

**Comment by wbloszyk** [comment]
This issue was resolved by add missing property. It can be close.
