### ISSUE TITLE
SeoProductIterator could not be registered, SourceIteratorInterface not found

### ISSUE THREAD

**Issue by tambait** [sonata-project/sandbox#823]
## Subject

During execution of `vendor/bin/phing`  multiple times I get warning that `SeoProductIterator` couldn't be registered. Also in IDE I get `Undefined type Exporter\Source\*` for all classes imported in `SeoProductIterator`.

If I prefix import of those classes with `Sonata` as in 'Sonata\Exporter\Source\SourceIteratorInterface' IDE message disappears.

## Steps to reproduce

Run `vendor/bin/phing` 

## Expected results

No warning messages.

## Actual results
```
[WARNING] Some commands could not be registered:                                                                       
In SeoProductIterator.php line 25:
                                                                 
  Interface 'Exporter\Source\SourceIteratorInterface' not found  
```

**Comment by wbloszyk** [comment]
@tambait Thank you for reporting this.

Change `sonata-project/exporter` vertsion in `composer.json` to:
```json
"sonata-project/exporter": "^1.8",
```

**Comment by wbloszyk** [comment]
@OskarStark Can you revert it of fix it? 
https://github.com/sonata-project/sandbox/pull/648

**Comment by tambait** [comment]
I also receive multiple errors like

`00:05:36 CRITICAL  [app] [FormatterBundle::transform] markdown - Error while parsing twig template : Unknown "gist" tag in "__string_template__a510690fe22758d789dcd5416aecf17a48bd54f49f607dd1cf335060288f7104" at line 5. ["text" => """  <h3>Gist Formatter</h3>\n  \n  <p>Now a specific gist from github</p>\n  \n  <p><% gist '1552362', 'gistfile1.txt'`

**Comment by wbloszyk** [comment]
I know about this errors. It is depends on twig extension (tag) which should replace text to gihtub gist. It is use in post example so you can ignore it.

**Comment by VincentLanglet** [comment]
Where is the SeoProductIterator class ?
Instead of change the version of exporter, the import should just be fixed.

I found one in ecommerce, but the exporter dependency is not required. (it should be)
https://github.com/sonata-project/ecommerce/blob/3.x/composer.json

**Comment by tambait** [comment]
I was looking the one in ecommerce, `vendor/sonata-project/ecommerce/src/Component/Product/SeoProductIterator.php`

**Comment by VincentLanglet** [comment]
It was fixed but never released https://github.com/sonata-project/ecommerce/commit/e021e9c8e07703acc3a33dbccedab9f455d3c149

But, IMHO the exporter version should be set in the sonata-project/ecommerce bundle.
If previously we had `sonata-exporter: ^1.8` on ecommerce this issue wouldn't happen.

Do you agree @wbloszyk @tambait ?

If so, 
- A PR is needed on ecommerce to add `sonata-exporter: ^2.3` as requirement.
- Then a new release

**Comment by tambait** [comment]
Fixed by [ sonata-project/ecommerce@726](https://github.com/sonata-project/ecommerce/pull/726)
