### ISSUE TITLE
Sonata Media config error

### ISSUE THREAD

**Issue by rpcjacobs** [sonata-project/sandbox#904]
The following line;

https://github.com/sonata-project/sandbox/blob/dcb9250154e0713d86962379618174857c7b897e/config/packages/sonata_media.yaml#L100

Prevents installing or updating (which i just started doing), it needs a space;
`mode: inset`

Just my 2c's!

**Comment by franmomu** [comment]
Thanks for reporting @rpcjacobs! Would you like to provide a PR fixing this issue?
