### ISSUE TITLE
Add vagrant configuration

### ISSUE THREAD

**Issue by nicolas-bastien** [sonata-project/sandbox#98]
Hi, would be great to have vagrant configuration.

And by the way for installation, I use Makefile to ease it.

As you have a lot of command line to to when install your bundle, and a make install command can help you to remove a lot of documentation and support for this installation...... maybe it can help

**Comment by Cyruxx** [comment]
Ping - This is definitely required; I'm not even working without e.g. puphpet.com anymore.

**Comment by jordisala1991** [comment]
Vagrant is already on the 3.0 branch
